openapi/openapi-generator/src/main/resources/openapi/templates/kora/kotlinModel.mustache

OpenAPI Generator Kotlin class without fields equals & hashCode contract missing fixed

OpenAPI Kotlin class equals & hashCode fix

---

annotation-processor-common/src/main/java/ru/tinkoff/kora/annotation/processor/common/TagUtils.java
database/database-annotation-processor/src/main/java/ru/tinkoff/kora/database/annotation/processor/cassandra/CassandraRepositoryGenerator.java
database/database-annotation-processor/src/main/java/ru/tinkoff/kora/database/annotation/processor/jdbc/JdbcRepositoryGenerator.java
database/database-annotation-processor/src/main/java/ru/tinkoff/kora/database/annotation/processor/jdbc/JdbcTypes.java
database/database-annotation-processor/src/test/java/ru/tinkoff/kora/database/common/annotation/processor/jdbc/AbstractJdbcRepositoryTest.java
database/database-annotation-processor/src/test/java/ru/tinkoff/kora/database/common/annotation/processor/jdbc/JdbcMacrosTest.java
database/database-annotation-processor/src/test/java/ru/tinkoff/kora/database/common/annotation/processor/jdbc/JdbcResultsTest.java
database/database-symbol-processor/src/main/kotlin/ru/tinkoff/kora/database/symbol/processor/jdbc/JdbcRepositoryGenerator.kt
database/database-symbol-processor/src/main/kotlin/ru/tinkoff/kora/database/symbol/processor/jdbc/JdbcTypes.kt
database/database-symbol-processor/src/test/kotlin/ru/tinkoff/kora/database/symbol/processor/jdbc/JdbcSuspendResultsTest.kt
symbol-processor-common/src/main/kotlin/ru/tinkoff/kora/ksp/common/TagUtils.kt

- JDBC CompletionStage signature support fixed
- Executor unused when `executorTag` specified fixed

JDBC async signature fixes

---

annotation-processor-common/src/main/java/ru/tinkoff/kora/annotation/processor/common/AbstractKoraProcessor.java

Gradle warning removed
```
warning: Supported source version 'RELEASE_17' from annotation processor 'org.gradle.api.internal.tasks.compile.processing.TimeTrackingProcessor' less than -source '21'
warning: Supported source version 'RELEASE_17' from annotation processor 'org.gradle.api.internal.tasks.compile.processing.TimeTrackingProcessor' less than -source '21'
warning: Supported source version 'RELEASE_17' from annotation processor 'org.gradle.api.internal.tasks.compile.processing.TimeTrackingProcessor' less than -source '21'
warning: Supported source version 'RELEASE_17' from annotation processor 'org.gradle.api.internal.tasks.compile.processing.TimeTrackingProcessor' less than -source '21'
warning: Supported source version 'RELEASE_17' from annotation processor …
```

Gradle warning removed

---

json/json-symbol-processor/src/main/kotlin/ru/tinkoff/kora/json/ksp/reader/JsonReaderGenerator.kt
json/json-symbol-processor/src/main/kotlin/ru/tinkoff/kora/json/ksp/writer/JsonWriterGenerator.kt
json/json-symbol-processor/src/test/kotlin/ru/tinkoff/kora/json/ksp/SpecialCharsInJsonFieldsTest.kt

I fixed generation of Kotlin JsonReaders/JsonWriters for data classes with props with `$` sign in name and in `@JsonField`.
Now it's possible to write:
```
@Json
data class DtoWithDollarFields(
val `$ref`: String,
val `ref$`: String,
@JsonField("\$\$ref")
val ref: String,
)
```

Fix JsonReader/JsonWriter for JSON fields with '$' in name

---

annotation-processor-common/src/main/java/ru/tinkoff/kora/annotation/processor/common/TagUtils.java
database/database-annotation-processor/src/main/java/ru/tinkoff/kora/database/annotation/processor/RepositoryBuilder.java
database/database-annotation-processor/src/main/java/ru/tinkoff/kora/database/annotation/processor/extension/RepositoryKoraExtension.java
database/database-annotation-processor/src/test/java/ru/tinkoff/kora/database/common/annotation/processor/ExtensionTest.java
database/database-annotation-processor/src/test/java/ru/tinkoff/kora/database/common/annotation/processor/TagPropagationTest.java
database/database-annotation-processor/src/test/java/ru/tinkoff/kora/database/common/annotation/processor/app/TestKoraAppExecutorTagged.java
database/database-annotation-processor/src/test/java/ru/tinkoff/kora/database/common/annotation/processor/app/TestKoraAppRepoTagged.java
database/database-symbol-processor/src/main/kotlin/ru/tinkoff/kora/database/symbol/processor/RepositoryBuilder.kt
database/database-symbol-processor/src/main/kotlin/ru/tinkoff/kora/database/symbol/processor/extension/RepositoryKoraExtension.kt
database/database-symbol-processor/src/test/kotlin/ru/tinkoff/kora/database/symbol/processor/ExtensionTest.kt
database/database-symbol-processor/src/test/kotlin/ru/tinkoff/kora/database/symbol/processor/RepositoryTagPropagationTest.kt
database/database-symbol-processor/src/test/kotlin/ru/tinkoff/kora/database/symbol/processor/jdbc/JdbcExtensionTests.kt
kora-app-annotation-processor/src/main/java/ru/tinkoff/kora/kora/app/annotation/processor/component/DependencyClaim.java
kora-app-symbol-processor/src/main/kotlin/ru/tinkoff/kora/kora/app/ksp/component/DependencyClaim.kt
kora-app-symbol-processor/src/main/kotlin/ru/tinkoff/kora/kora/app/ksp/declaration/ComponentDeclaration.kt
symbol-processor-common/src/main/kotlin/ru/tinkoff/kora/ksp/common/TagUtils.kt

I noticed that it's impossible to put tags on `@Repository` interfaces:
```kotlin
@Repository
@Tag(MyRepo::class) // Impl won't have this Tag
interface MyRepo : JdbcRepository
```
The only current workaround for this issue:
```kotlin
interface MyRepoModule {
@Tag(MyRepo::class)
fun myRepo(factory: JdbcConnectionFactory) = `\$MyRepo_Impl`(factory)
}
```
I think this is unnecessary complication, so in this PR I adding `@Tag` propagation from `@Repository` marked interface/abstract class to it's generated `Impl`

Added Tag propagation for Repository codegen

---

openapi/openapi-generator/src/test/resources/example/petstoreV3_validation.yaml
validation/validation-annotation-processor/src/test/java/ru/tinkoff/kora/validation/annotation/processor/ValidateRunner.java
validation/validation-annotation-processor/src/test/java/ru/tinkoff/kora/validation/annotation/processor/testdata/ValidateFlux.java
validation/validation-annotation-processor/src/test/java/ru/tinkoff/kora/validation/annotation/processor/testdata/ValidateFuture.java
validation/validation-annotation-processor/src/test/java/ru/tinkoff/kora/validation/annotation/processor/testdata/ValidateMono.java
validation/validation-annotation-processor/src/test/java/ru/tinkoff/kora/validation/annotation/processor/testdata/ValidateSync.java
validation/validation-symbol-processor/src/main/kotlin/ru/tinkoff/kora/validation/symbol/processor/aop/ValidateMethodKoraAspect.kt
validation/validation-symbol-processor/src/test/kotlin/ru/tinkoff/kora/validation/symbol/processor/ValidateRunner.kt
validation/validation-symbol-processor/src/test/kotlin/ru/tinkoff/kora/validation/symbol/processor/testdata/ValidateFlow.kt
validation/validation-symbol-processor/src/test/kotlin/ru/tinkoff/kora/validation/symbol/processor/testdata/ValidateSuspend.kt
validation/validation-symbol-processor/src/test/kotlin/ru/tinkoff/kora/validation/symbol/processor/testdata/ValidateSync.kt

ValidateMethodKoraAspect pattern and other string parameters fixed (closes #90 )

Method argument Pattern validation fixed

---

openapi/openapi-generator/src/main/resources/openapi/templates/kora/javaClientApi.mustache
openapi/openapi-generator/src/main/resources/openapi/templates/kora/kotlinClientApi.mustache

Javadoc for deprecated OpenAPI method contains `@deprecated` marker. See example below:
```java
/**
* GET /api/v2/my_url
* Получение чего-там )
*
* @param *** (required)
* @param *** (required)
* @param *** (required)
* @return Получение ответа (status code 200)
*         or Сообщение об ошибке (status code 400)
* @deprecated
*/
@ru.tinkoff.kora.http.common.annotation.HttpRoute(method = "GET", path = "/api/v2/my_url")
@ru.tinkoff.kora.http.client.common.annotation.ResponseCodeMapper(code = 200, mapper = ApiResponseMapper.class)
ApiResponse getResponse(      
@ru.tinkoff.kora.http.common.annotation.Path("param")
String param,
```
And after compilation there was a warning like that:
```
.../MyApi.java:165: warning: [dep-ann] deprecated item is not annotated with @Deprecated
ApiResponse …
```

Add `@Deprecated` annotation for OpenAPI generated HTTP Client methods

---

http/http-client-common/src/main/java/ru/tinkoff/kora/http/client/common/request/HttpClientRequestMapperModule.java

HttpClientRequestMapperModule string mapping as plain text by default (fixed #150 )

HttpClientRequestMapper String as plain text

---

annotation-processor-common/src/testFixtures/java/ru/tinkoff/kora/annotation/processor/common/TestUtils.java
kora-app-annotation-processor/src/main/java/ru/tinkoff/kora/kora/app/annotation/processor/KoraAppProcessor.java
kora-app-annotation-processor/src/main/java/ru/tinkoff/kora/kora/app/annotation/processor/KoraAppUtils.java
kora-app-annotation-processor/src/test/java/ru/tinkoff/kora/kora/app/annotation/processor/KoraAppProcessorTest.java
kora-app-annotation-processor/src/test/java/ru/tinkoff/kora/kora/app/annotation/processor/app/AppWithAppPartAppWithSubmodule.java
kora-app-symbol-processor/src/main/kotlin/ru/tinkoff/kora/kora/app/ksp/KoraAppProcessor.kt
kora-app-symbol-processor/src/test/kotlin/ru/tinkoff/kora/kora/app/ksp/KoraAppKspTest.kt
symbol-processor-common/src/main/kotlin/ru/tinkoff/kora/ksp/common/BaseSymbolProcessor.kt
symbol-processor-common/src/testFixtures/kotlin/ru/tinkoff/kora/ksp/common/AbstractSymbolProcessorTest.kt
symbol-processor-common/src/testFixtures/kotlin/ru/tinkoff/kora/ksp/common/TestUtils.kt
validation/validation-symbol-processor/src/main/kotlin/ru/tinkoff/kora/validation/symbol/processor/ValidSymbolProcessor.kt

Allow `@KoraApp` generate `@SubModule` if specific annotation processor option is applied
Also allow to use external `@KoraApp` generated graph as `@SubModule` in current processing `@KoraApp`, this will allow to extend other KoraApp generated graph
This can be useful in tests, to generate enriched test Graph with extra functionality and all src application `@KoraApp` graph as base
Behavior is disabled by default and can be enabled via annotation processor options - `kora.app.submodule.enabled=true`

`@KoraApp` generate `@SubModule` if enabled

---

openapi/openapi-generator/src/main/java/ru/tinkoff/kora/openapi/generator/KoraCodegen.java
openapi/openapi-generator/src/main/resources/openapi/templates/kora/javaClientApi.mustache
openapi/openapi-generator/src/main/resources/openapi/templates/kora/kotlinClientApi.mustache
openapi/openapi-generator/src/test/java/ru/tinkoff/kora/openapi/generator/KoraCodegenTest.java

OpenAPI generator authAsMethodArgument option support added

OpenAPI HTTP client auth as method argument

---

openapi/openapi-generator/src/main/java/ru/tinkoff/kora/openapi/generator/KoraCodegen.java
openapi/openapi-generator/src/main/resources/openapi/templates/kora/javaAsyncServerApi.mustache
openapi/openapi-generator/src/main/resources/openapi/templates/kora/javaServerApi.mustache
openapi/openapi-generator/src/main/resources/openapi/templates/kora/kotlinServerApi.mustache

OpenAPI Codegen allows aspects if only additionalContractAnnotations specified without validation enabled

OpenAPI Codegen allows additionalContractAnnotations without validation

---

openapi/openapi-generator/src/main/java/ru/tinkoff/kora/openapi/generator/KoraCodegen.java
openapi/openapi-generator/src/main/resources/openapi/templates/kora/javaModel.mustache
openapi/openapi-generator/src/main/resources/openapi/templates/kora/kotlinModel.mustache
openapi/openapi-generator/src/test/java/ru/tinkoff/kora/openapi/generator/KoraCodegenTest.java
openapi/openapi-generator/src/test/resources/example/petstoreV3_discriminator.yaml
openapi/openapi-generator/src/test/resources/example/petstoreV3_nullable.yaml

OpenAPI enableJsonNullable option support added

---

database/database-annotation-processor/src/main/java/ru/tinkoff/kora/database/annotation/processor/jdbc/JdbcNativeTypes.java
database/database-symbol-processor/src/main/kotlin/ru/tinkoff/kora/database/symbol/processor/jdbc/JdbcNativeTypes.kt

This MR fixes the following bug:
Kora generates incorrect parameter binding for `@Nullable byte[]` parameters in JdbcRepository.
Consider the repository interface:
```kotlin
interface BytesRepo : JdbcRepository {
@Query(
"""
INSERT INTO bytes_table (bytes_col)
VALUES (:bytes)
""",
)
fun insertBytes(bytes: ByteArray?) // bytes is nullable
}
```
```kotlin
bytes.let {
if (it == null) {
_stmt.setNull(1, Types.NUMERIC)
} else {
_stmt.setBytes(1, it)
}
}
```
The above code leads to SQLException
Generated code contains:
```kotlin
_stmt.setBytes(1, bytes)
```
As `setBytes` accepts `null`.
Or fixed version of the current variant (with proper sql type):
```
bytes.let {
if (it == null) {
_stmt.setNull(1, Types.VARBINARY)
} else {
_stmt.setBytes(1, it)
}
}
```

Fix sql.Types in JdbcNativeType.bindNull for byte[]

---

scheduling/scheduling-quartz/src/main/java/ru/tinkoff/kora/scheduling/quartz/KoraQuartzJobRegistrar.java

- NPE is occured in **KoraQuartzJobRegistrar** if **oldTrigger.getEndTime()** is null (**endTime** can be unspecified));
Stacktrace (message: **_Error on checking config for changes_** in **ru.tinkoff.kora.config.common.ConfigWatcher**): 
```
java.lang.NullPointerException: Cannot invoke "java.util.Date.equals(Object)" because the return value of "org.quartz.Trigger.getEndTime()" is null
at ru.tinkoff.kora.scheduling.quartz.KoraQuartzJobRegistrar.triggersEqual(KoraQuartzJobRegistrar.java:65)
at ru.tinkoff.kora.scheduling.quartz.KoraQuartzJobRegistrar.init(KoraQuartzJobRegistrar.java:49)
at ru.tinkoff.kora.application.graph.internal.GraphImpl$TmpGraph.lambda$initializeNode$6(GraphImpl.java:513)
at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
at …
```

quartz job registrar npe is fixed

---

cache/cache-annotation-processor/src/test/java/ru/tinkoff/kora/cache/annotation/processor/CacheRunner.java
cache/cache-redis/build.gradle
cache/cache-redis/src/main/java/ru/tinkoff/kora/cache/redis/AbstractRedisCache.java
cache/cache-redis/src/main/java/ru/tinkoff/kora/cache/redis/RedisCacheClient.java
cache/cache-redis/src/main/java/ru/tinkoff/kora/cache/redis/RedisCacheMapperModule.java
cache/cache-redis/src/main/java/ru/tinkoff/kora/cache/redis/lettuce/LettuceClientConfig.java
cache/cache-redis/src/main/java/ru/tinkoff/kora/cache/redis/lettuce/LettuceClientFactory.java
cache/cache-redis/src/main/java/ru/tinkoff/kora/cache/redis/lettuce/LettuceClusterRedisCacheClient.java
cache/cache-redis/src/main/java/ru/tinkoff/kora/cache/redis/lettuce/LettuceModule.java
cache/cache-redis/src/main/java/ru/tinkoff/kora/cache/redis/lettuce/LettuceRedisCacheClient.java
cache/cache-redis/src/test/java/ru/tinkoff/kora/cache/redis/AbstractAsyncCacheTests.java
cache/cache-redis/src/test/java/ru/tinkoff/kora/cache/redis/AbstractSyncCacheTests.java
cache/cache-redis/src/test/java/ru/tinkoff/kora/cache/redis/AsyncCacheExpireReadTests.java
cache/cache-redis/src/test/java/ru/tinkoff/kora/cache/redis/AsyncCacheExpireWriteTests.java
cache/cache-redis/src/test/java/ru/tinkoff/kora/cache/redis/CacheRunner.java
cache/cache-redis/src/test/java/ru/tinkoff/kora/cache/redis/SyncCacheExpireReadTests.java
cache/cache-redis/src/test/java/ru/tinkoff/kora/cache/redis/SyncCacheExpireWriteTests.java
cache/cache-redis/src/test/java/ru/tinkoff/kora/cache/redis/SyncCacheTests.java
cache/cache-redis/src/test/java/ru/tinkoff/kora/cache/redis/testdata/DummyCache.java
cache/cache-symbol-processor/src/test/kotlin/ru/tinkoff/kora/cache/symbol/processor/CacheRunner.kt
dependencies.gradle

- RedisCacheClient `mget#hasValue()` fixed
- RedisCacheClient pool support for pipeline command for mset and pget commands with expire

Cache Redis multiple key get fix

---

openapi/openapi-generator/src/main/java/ru/tinkoff/kora/openapi/generator/KoraCodegen.java

OpenAPI `typeMapping` parameter overriden with primitive Java types removed

OpenAPI typeMapping fixed

---

experimental/camunda-zeebe-worker/src/main/java/ru/tinkoff/kora/camunda/zeebe/worker/ZeebeManagedChannelFactory.java
grpc/grpc-client-annotation-processor/src/main/java/ru/tinkoff/grpc/client/annotation/processor/GrpcClientExtension.java
grpc/grpc-client-annotation-processor/src/test/java/ru/tinkoff/grpc/client/annotation/processor/GrpcClientExtensionTest.java
grpc/grpc-client-symbol-processor/src/main/kotlin/ru.tinkoff.grpc.client.ksp/GrpcClientExtension.kt
grpc/grpc-client-symbol-processor/src/test/kotlin/ru/tinkoff/grpc/client/ksp/GrpcClientExtensionTest.kt
grpc/grpc-client/src/main/java/ru/tinkoff/grpc/client/GrpcClientBuilderConfigurer.java
grpc/grpc-client/src/main/java/ru/tinkoff/grpc/client/GrpcClientModule.java
grpc/grpc-client/src/main/java/ru/tinkoff/grpc/client/GrpcNettyClientChannelFactory.java
grpc/grpc-client/src/main/java/ru/tinkoff/grpc/client/ManagedChannelLifecycle.java
grpc/grpc-client/src/main/java/ru/tinkoff/grpc/client/config/DefaultServiceConfig.java
grpc/grpc-client/src/main/java/ru/tinkoff/grpc/client/config/DefaultServiceConfigConfigValueExtractor.java
grpc/grpc-client/src/main/java/ru/tinkoff/grpc/client/config/GrpcClientConfig.java
grpc/grpc-server/src/main/java/ru/tinkoff/kora/grpc/server/GrpcServerBuilderConfigurer.java
grpc/grpc-server/src/main/java/ru/tinkoff/kora/grpc/server/GrpcServerModule.java

- Introduced `GrpcClientBuilderConfigurer` and `GrpcServerBuilderConfigurer` interfaces.
- Updated grpc client module to use [service config](https://grpc.io/docs/guides/service-config/) from application configuration.

More flexible way of grpc component configuration

---

test/test-junit5/src/main/java/ru/tinkoff/kora/test/extension/junit5/KoraJUnit5Extension.java
test/test-junit5/src/test/java/ru/tinkoff/kora/test/extension/junit5/mockito/MockOnlyTests.java

KoraJUnit5Extension do not exclude mock components from graph root, so their nodes will stay in Graph or they can't be mocked cause not found in graph

JUnit5 mock component not found in graph fixed

---

http/http-server-undertow/src/main/java/ru/tinkoff/kora/http/server/undertow/UndertowHttpHeaders.java
http/http-server-undertow/src/main/java/ru/tinkoff/kora/http/server/undertow/request/UndertowPublicApiRequest.java

Optimize `List.copyOf()` and `Map.copyOf()` usage with unmodifiable collections wrappers

HTTP Server query and header retrieval optimized

---

test/test-junit5/src/main/java/ru/tinkoff/kora/test/extension/junit5/KoraJUnit5Extension.java
test/test-junit5/src/main/java/ru/tinkoff/kora/test/extension/junit5/TestGraphInitialized.java
test/test-junit5/src/test/java/ru/tinkoff/kora/test/extension/junit5/initializemode/FieldPerClassTests.java
test/test-junit5/src/test/java/ru/tinkoff/kora/test/extension/junit5/initializemode/FieldPerMethodTests.java
test/test-junit5/src/test/java/ru/tinkoff/kora/test/extension/junit5/initializemode/MethodPerClassTests.java
test/test-junit5/src/test/java/ru/tinkoff/kora/test/extension/junit5/initializemode/MethodPerMethodTests.java
test/test-junit5/src/test/java/ru/tinkoff/kora/test/extension/junit5/initializemode/NestedFieldPerClassTests.java
test/test-junit5/src/test/java/ru/tinkoff/kora/test/extension/junit5/initializemode/NestedFieldPerMethodTests.java
test/test-junit5/src/test/java/ru/tinkoff/kora/test/extension/junit5/mockito/MockAndFullGraphTests.java
test/test-junit5/src/test/java/ru/tinkoff/kora/test/extension/junit5/mockito/MockOnlyTests.java
test/test-junit5/src/test/java/ru/tinkoff/kora/test/extension/junit5/mockito/MockWrappedTests.java
test/test-junit5/src/test/java/ru/tinkoff/kora/test/extension/junit5/replace/ReplaceWrappedTests.java
test/test-junit5/src/test/java/ru/tinkoff/kora/test/extension/junit5/testdata/TestApplication.java

Inject full Graph with mocked parts and not consider mocks as roots when only mocks are specified

JUnit extension full graph only with mocked parts fixed

---

grpc/grpc-server/src/main/java/ru/tinkoff/kora/grpc/server/GrpcServerModule.java
grpc/grpc-server/src/main/java/ru/tinkoff/kora/grpc/server/config/GrpcServerConfig.java

adding 
https://grpc.github.io/grpc-java/javadoc/io/grpc/netty/NettyServerBuilder.html#maxConnectionAge(long,java.util.concurrent.TimeUnit)
https://grpc.github.io/grpc-java/javadoc/io/grpc/netty/NettyServerBuilder.html#maxConnectionAgeGrace(long,java.util.concurrent.TimeUnit)
props to GrpcServer config
Our devops says that we have some network policy, which restricts connection lifetime, so we should be able to finish our connections before this policy will kill them.
Also we see next grpc-errors in logs: "Cancellation received from client"

adding maxConnectionAge and maxConnectionAgeGrace configs to grpcServer

---

json/json-common/src/main/java/ru/tinkoff/kora/json/common/JsonObjectCodec.java

Replace HashMap with LinkedHashMap to preserve fields order for JsonReader<Object>

Replace HashMap with LinkedHashMap to preserve fields order 

---

annotation-processor-common/src/main/java/ru/tinkoff/kora/annotation/processor/common/CommonUtils.java
cache/cache-annotation-processor/src/main/java/ru/tinkoff/kora/cache/annotation/processor/CacheAnnotationProcessor.java
cache/cache-symbol-processor/src/main/kotlin/ru/tinkoff/kora/cache/symbol/processor/CacheSymbolProcessor.kt
database/database-symbol-processor/src/main/kotlin/ru/tinkoff/kora/database/symbol/processor/RepositoryBuilder.kt
experimental/s3-client-annotation-processor/src/main/java/ru/tinkoff/kora/s3/client/annotation/processor/S3ClientAnnotationProcessor.java
experimental/s3-client-symbol-processor/src/main/kotlin/ru/tinkoff/kora/s3/client/symbol/processor/S3ClientSymbolProcessor.kt
http/http-client-symbol-processor/src/main/kotlin/ru/tinkoff/kora/http/client/symbol/processor/ClientClassGenerator.kt
kafka/kafka-symbol-processor/src/main/kotlin/ru/tinkoff/kora/kafka/symbol/processor/producer/KafkaPublisherGenerator.kt
kafka/kafka-symbol-processor/src/main/kotlin/ru/tinkoff/kora/kafka/symbol/processor/producer/KafkaPublisherTransactionalGenerator.kt
symbol-processor-common/src/main/kotlin/ru/tinkoff/kora/ksp/common/CommonAopUtils.kt

Interfaces where impl is generated by AP later like `@HttpClient` with `default` AOP method support fixed

Generated impl support for interface `default` AOP method

---

experimental/s3-client-aws/src/main/java/ru/tinkoff/kora/s3/client/aws/AwsS3KoraAsyncClient.java
experimental/s3-client-aws/src/main/java/ru/tinkoff/kora/s3/client/aws/AwsS3KoraClient.java
experimental/s3-client-aws/src/main/java/ru/tinkoff/kora/s3/client/aws/AwsS3ObjectMeta.java

S3 aws client fix `AwsS3ObjectMeta` behavior with implementation replacement `objectAttributes` -> `headObject`

Fixed AWS S3 Client objectMeta method

---

kafka/kafka/src/main/java/ru/tinkoff/kora/kafka/common/consumer/telemetry/DefaultKafkaConsumerTelemetryFactory.java

Kafka Consumer Telemetry factory deprecated method support for old Kora libraries compatibility

Fixed Kafka Consumer Telemetry Deprecated method library compatibility

---

gradle/libs.versions.toml
test/test-junit5/build.gradle
test/test-junit5/src/main/java/ru/tinkoff/kora/test/extension/junit5/GraphMockitoMock.java
test/test-junit5/src/main/java/ru/tinkoff/kora/test/extension/junit5/GraphMockitoSpy.java
test/test-junit5/src/main/java/ru/tinkoff/kora/test/extension/junit5/GraphMockkMock.java
test/test-junit5/src/main/java/ru/tinkoff/kora/test/extension/junit5/GraphMockkSpyk.java
test/test-junit5/src/main/java/ru/tinkoff/kora/test/extension/junit5/GraphReplacementNoDeps.java
test/test-junit5/src/main/java/ru/tinkoff/kora/test/extension/junit5/GraphReplacementWithDeps.java
test/test-junit5/src/main/java/ru/tinkoff/kora/test/extension/junit5/GraphUtils.java
test/test-junit5/src/main/java/ru/tinkoff/kora/test/extension/junit5/KoraGraphModification.java
test/test-junit5/src/main/java/ru/tinkoff/kora/test/extension/junit5/KoraJUnit5Extension.java
test/test-junit5/src/main/java/ru/tinkoff/kora/test/extension/junit5/MockUtils.java
test/test-junit5/src/test/java/ru/tinkoff/kora/test/extension/junit5/replace/ReplaceComplexHolderDependencyTests.java
test/test-junit5/src/test/java/ru/tinkoff/kora/test/extension/junit5/replace/ReplaceComplexHolderTests.java
test/test-junit5/src/test/java/ru/tinkoff/kora/test/extension/junit5/replace/ReplaceComplexInterfaceHolderTests.java
test/test-junit5/src/test/java/ru/tinkoff/kora/test/extension/junit5/replace/ReplaceComplexOtherDependencyTests.java
test/test-junit5/src/test/java/ru/tinkoff/kora/test/extension/junit5/replace/ReplaceComplexOtherTests.java
test/test-junit5/src/test/java/ru/tinkoff/kora/test/extension/junit5/replace/ReplaceComplexWrappedDependencyTests.java
test/test-junit5/src/test/java/ru/tinkoff/kora/test/extension/junit5/replace/ReplaceComplexWrappedTests.java
test/test-junit5/src/test/java/ru/tinkoff/kora/test/extension/junit5/testdata/TestApplication.java

JUnit test reinforced `Wrapped` support with complex type check and mocking if possible to exclude potential type misalignment when node type is more than just `Wrapped` and is indeed an instance and inherits `Wrapped` behavior

Fixed JUnit testing complex `Wrapped` support

---

build.gradle
gradle/libs.versions.toml
openapi/openapi-generator/src/main/java/ru/tinkoff/kora/openapi/generator/KoraCodegen.java

OpenAPI generator updated to 7.16.0 (breaking change) (requires OpenAPI plugin update to `7.16.0`)

OpenAPI generator updated

---

resilient/resilient-kora/src/main/java/ru/tinkoff/kora/resilient/circuitbreaker/KoraCircuitBreaker.java
resilient/resilient-kora/src/test/java/ru/tinkoff/kora/resilient/circuitbreaker/KoraCircuitBreakerTests.java

Fixed KoraCircuitBreaker release ignored exceptions in HALF_OPEN state

Fixed KoraCircuitBreaker release ignored exceptions in HALF_OPEN state
