.github/workflows/publish-release.yml, .github/workflows/publish-snapshot.yml, .github/workflows/test-job/action.yml, .github/workflows/test-master.yml, .github/workflows/test-pr.yml, README.md
=> CI updated

openapi/openapi-generator/src/main/java/ru/tinkoff/kora/openapi/generator/KoraCodegen.java, openapi/openapi-generator/src/test/java/ru/tinkoff/kora/openapi/generator/KoraCodegenTest.java, openapi/openapi-generator/src/test/resources/example/petstoreV3_discriminator.yaml, openapi/openapi-generator/src/test/resources/example/petstoreV3_request_parameters.yaml
- MapperTag for `@Json` is placed only for `application/json` & `text/json`
=> OpenAPI Non Json content type mapper fixed

openapi/openapi-generator/src/main/java/ru/tinkoff/kora/openapi/generator/KoraCodegen.java, openapi/openapi-generator/src/main/resources/openapi/templates/kora/javaAsyncServerApi.mustache, openapi/openapi-generator/src/main/resources/openapi/templates/kora/javaAsyncServerApiDelegate.mustache
- OpenAPI Java Async & Reactive mode fixed
- requestInDelegateParams support for Async & Reactive contracts
=> OpenAPI Java Async & Reactive mode fixed

annotation-processor-common/src/main/java/ru/tinkoff/kora/annotation/processor/common/BuildEnvironment.java, kora-app-annotation-processor/src/main/java/ru/tinkoff/kora/kora/app/annotation/processor/KoraAppProcessor.java, kora-app-symbol-processor/src/main/kotlin/ru/tinkoff/kora/kora/app/ksp/KoraAppProcessor.kt
Features:
- Annotation processors logging improved
=> Annotation processors logging improved

cache/cache-annotation-processor/src/main/java/ru/tinkoff/kora/cache/annotation/processor/aop/CacheInvalidateAopKoraAspect.java
Features:
- CacheInvalidateAopKoraAspect for reactor fixed
=> Cache Redis AOP fixes

http/http-common/src/main/java/ru/tinkoff/kora/http/common/header/HttpHeaders.java, http/http-common/src/main/java/ru/tinkoff/kora/http/common/header/HttpHeadersEmpty.java, http/http-server-undertow/src/main/java/ru/tinkoff/kora/http/server/undertow/UndertowExchangeProcessor.java
- UndertowExchangeProcessor Exchange already complete fixed
- UndertowExchangeProcessor sendStreamingBody headers support fixed
- HttpHeaders#empty added
=> Undertow exchange already complete fixed

cache/cache-annotation-processor/src/main/java/ru/tinkoff/kora/cache/annotation/processor/aop/CacheInvalidateAopKoraAspect.java, cache/cache-annotation-processor/src/main/java/ru/tinkoff/kora/cache/annotation/processor/aop/CachePutAopKoraAspect.java, cache/cache-annotation-processor/src/main/java/ru/tinkoff/kora/cache/annotation/processor/aop/CacheableAopKoraAspect.java, cache/cache-annotation-processor/src/test/java/ru/tinkoff/kora/cache/annotation/processor/AsyncCacheManyOptionalAopTests.java, cache/cache-annotation-processor/src/test/java/ru/tinkoff/kora/cache/annotation/processor/AsyncCacheOptionalAopTests.java, cache/cache-annotation-processor/src/test/java/ru/tinkoff/kora/cache/annotation/processor/MonoCacheManyOptionalAopTests.java, cache/cache-annotation-processor/src/test/java/ru/tinkoff/kora/cache/annotation/processor/MonoCacheOptionalAopTests.java, cache/cache-annotation-processor/src/test/java/ru/tinkoff/kora/cache/annotation/processor/testdata/async/CacheableAsyncManyOptional.java, cache/cache-annotation-processor/src/test/java/ru/tinkoff/kora/cache/annotation/processor/testdata/async/CacheableAsyncOptional.java, cache/cache-annotation-processor/src/test/java/ru/tinkoff/kora/cache/annotation/processor/testdata/reactive/mono/CacheableMonoManyOptional.java, cache/cache-annotation-processor/src/test/java/ru/tinkoff/kora/cache/annotation/processor/testdata/reactive/mono/CacheableMonoOptional.java
- Cache AOP Optional argument for CompletionStage and Mono support added
- Cache AOP CompletionStage optimized
=> Cache AOP CompletionStage<Optional<T>> support

annotation-processor-common/src/main/java/ru/tinkoff/kora/annotation/processor/common/LogUtils.java, aop/aop-annotation-processor/src/main/java/ru/tinkoff/kora/aop/annotation/processor/AopAnnotationProcessor.java, aop/aop-annotation-processor/src/main/java/ru/tinkoff/kora/aop/annotation/processor/AopProcessor.java, config/config-annotation-processor/src/main/java/ru/tinkoff/kora/config/annotation/processor/ConfigParserGenerator.java, config/config-annotation-processor/src/main/java/ru/tinkoff/kora/config/annotation/processor/processor/ConfigParserAnnotationProcessor.java, database/database-annotation-processor/src/main/java/ru/tinkoff/kora/database/annotation/processor/RepositoryAnnotationProcessor.java, database/database-annotation-processor/src/main/java/ru/tinkoff/kora/database/annotation/processor/RepositoryBuilder.java, database/database-annotation-processor/src/main/java/ru/tinkoff/kora/database/annotation/processor/jdbc/extension/JdbcTypesExtension.java, database/database-symbol-processor/src/main/kotlin/ru/tinkoff/kora/database/symbol/processor/RepositoryBuilder.kt, json/json-annotation-processor/src/main/java/ru/tinkoff/kora/json/annotation/processor/JsonAnnotationProcessor.java, json/json-annotation-processor/src/main/java/ru/tinkoff/kora/json/annotation/processor/JsonProcessor.java, kora-app-annotation-processor/src/main/java/ru/tinkoff/kora/kora/app/annotation/processor/KoraAppProcessor.java, kora-app-annotation-processor/src/main/java/ru/tinkoff/kora/kora/app/annotation/processor/KoraAppUtils.java, kora-app-annotation-processor/src/main/java/ru/tinkoff/kora/kora/app/annotation/processor/extension/Extensions.java, kora-app-symbol-processor/src/main/kotlin/ru/tinkoff/kora/kora/app/ksp/KoraAppProcessor.kt
- Java Annotation Processor Logging improved
=> Java Annotation Processor Logging improved

cache/cache-annotation-processor/src/main/java/ru/tinkoff/kora/cache/annotation/processor/aop/CacheInvalidateAopKoraAspect.java, database/database-annotation-processor/src/main/java/ru/tinkoff/kora/database/annotation/processor/cassandra/extension/CassandraTypesExtension.java, database/database-annotation-processor/src/main/java/ru/tinkoff/kora/database/annotation/processor/entity/DbEntity.java, database/database-annotation-processor/src/main/java/ru/tinkoff/kora/database/annotation/processor/jdbc/JdbcRepositoryGenerator.java, http/http-server-annotation-processor/src/main/java/ru/tinkoff/kora/http/server/annotation/processor/RequestHandlerGenerator.java, json/json-annotation-processor/src/main/java/ru/tinkoff/kora/json/annotation/processor/writer/JsonWriterGenerator.java, openapi/openapi-generator/src/main/resources/openapi/templates/kora/javaClientResponseMappers.mustache, resilient/resilient-annotation-processor/src/main/java/ru/tinkoff/kora/resilient/annotation/processor/aop/CircuitBreakerKoraAspect.java, resilient/resilient-annotation-processor/src/main/java/ru/tinkoff/kora/resilient/annotation/processor/aop/FallbackKoraAspect.java, resilient/resilient-annotation-processor/src/main/java/ru/tinkoff/kora/resilient/annotation/processor/aop/RetryKoraAspect.java, validation/validation-annotation-processor/src/main/java/ru/tinkoff/kora/validation/annotation/processor/ValidatorGenerator.java
- Java 21 support with removed double quotes for imports in OpenAPI HTTP Client generation
- Double quotes useless removed (cleanup)
=> OpenAPI Generation Java 21 support

.github/ISSUE_TEMPLATE/bug_report.md, logging/declarative-logging/declarative-logging-annotation-processor/src/main/java/ru/tinkoff/kora/logging/aspect/LogAspect.java
- Codegen logging AOP improved
=> Logging AOP improved

resilient/resilient-annotation-processor/src/main/java/ru/tinkoff/kora/resilient/annotation/processor/aop/RetryKoraAspect.java, resilient/resilient-annotation-processor/src/test/java/ru/tinkoff/kora/resilient/annotation/processor/aop/RetryFutureTests.java, resilient/resilient-kora/src/main/java/ru/tinkoff/kora/resilient/retry/KoraRetry.java, resilient/resilient-kora/src/main/java/ru/tinkoff/kora/resilient/retry/Retry.java
- RetryKoraAspect optimized for CompletableStage
- Retry#retry for CompletableStage added
=> Resilient Retry AOP for CompletableStage improved

resilient/resilient-annotation-processor/src/main/java/ru/tinkoff/kora/resilient/annotation/processor/aop/CircuitBreakerKoraAspect.java, resilient/resilient-annotation-processor/src/main/java/ru/tinkoff/kora/resilient/annotation/processor/aop/FallbackKoraAspect.java, resilient/resilient-annotation-processor/src/main/java/ru/tinkoff/kora/resilient/annotation/processor/aop/TimeoutKoraAspect.java, resilient/resilient-symbol-processor/src/main/kotlin/ru/tinkoff/kora/resilient/symbol/processor/aop/FallbackKoraAspect.kt
- Resilient CircuitBreaker prefailed future fixed
- Resilient parameter name collision fixed
=> Resilient minor fixes

kora-app-annotation-processor/src/main/java/ru/tinkoff/kora/kora/app/annotation/processor/GraphBuilder.java, kora-app-annotation-processor/src/main/java/ru/tinkoff/kora/kora/app/annotation/processor/KoraAppProcessor.java
- GraphBuilder improve info exception if component not found non-last-round
=> Component build message improved

http/http-client-async/src/main/java/ru/tinkoff/kora/http/client/async/response/AsyncHttpClientStreamingResponseBody.java, http/http-client-jdk/src/main/java/ru/tinkoff/kora/http/client/jdk/JdkHttpClientResponse.java, http/http-client-ok/src/main/java/ru/tinkoff/kora/http/client/ok/OkHttpRequestBody.java, http/http-client-ok/src/main/java/ru/tinkoff/kora/http/client/ok/OkHttpResponseBody.java, http/http-common/src/main/java/ru/tinkoff/kora/http/common/body/HttpBodyOutput.java, http/http-common/src/main/java/ru/tinkoff/kora/http/common/body/StreamingHttpBodyInput.java, http/http-common/src/main/java/ru/tinkoff/kora/http/common/body/StreamingHttpBodyOutput.java, http/http-server-undertow/src/main/java/ru/tinkoff/kora/http/server/undertow/request/UndertowRequestHttpBody.java
HTTP Content-Length fixed in impls
=> HTTP Content-Length fixed

openapi/openapi-generator/src/main/resources/openapi/templates/kora/kotlinEnumClass.mustache, openapi/openapi-generator/src/test/java/ru/tinkoff/kora/openapi/generator/KoraCodegenTest.java, openapi/openapi-generator/src/test/resources/example/petstoreV3_enum.yaml
kotlinEnumClass.mustache nullable enum fixed
=> OpenApi Kotlin Nullable enum fixed

resilient/resilient-annotation-processor/src/main/java/ru/tinkoff/kora/resilient/annotation/processor/aop/RetryKoraAspect.java, resilient/resilient-annotation-processor/src/test/java/ru/tinkoff/kora/resilient/annotation/processor/aop/CircuitBreakerFutureTests.java, resilient/resilient-annotation-processor/src/test/java/ru/tinkoff/kora/resilient/annotation/processor/aop/FallbackFutureTests.java, resilient/resilient-annotation-processor/src/test/java/ru/tinkoff/kora/resilient/annotation/processor/aop/RetryFutureTests.java, resilient/resilient-annotation-processor/src/test/java/ru/tinkoff/kora/resilient/annotation/processor/aop/TimeoutFutureTests.java, resilient/resilient-annotation-processor/src/test/java/ru/tinkoff/kora/resilient/annotation/processor/aop/testdata/CircuitBreakerTarget.java, resilient/resilient-annotation-processor/src/test/java/ru/tinkoff/kora/resilient/annotation/processor/aop/testdata/FallbackTarget.java, resilient/resilient-annotation-processor/src/test/java/ru/tinkoff/kora/resilient/annotation/processor/aop/testdata/RetryTarget.java, resilient/resilient-annotation-processor/src/test/java/ru/tinkoff/kora/resilient/annotation/processor/aop/testdata/TimeoutTarget.java
RetryKoraAspect CompletableFuture return signature fix
=> `@Retry` CompletableFuture fixed

cache/cache-annotation-processor/src/main/java/ru/tinkoff/kora/cache/annotation/processor/CacheOperationUtils.java, cache/cache-symbol-processor/src/main/kotlin/ru/tinkoff/kora/cache/symbol/processor/CacheOperationUtils.kt
Cacheable and CacheEvict error message improved
=> Cache AOP error handling improved 

http/http-client-common/src/main/java/ru/tinkoff/kora/http/client/common/interceptor/BasicAuthHttpClientInterceptor.java, http/http-client-common/src/main/java/ru/tinkoff/kora/http/client/common/interceptor/BearerAuthHttpClientInterceptor.java, openapi/openapi-generator/src/main/java/ru/tinkoff/kora/openapi/generator/KoraCodegen.java, openapi/openapi-generator/src/main/resources/openapi/templates/kora/javaClientSecuritySchema.mustache, openapi/openapi-generator/src/main/resources/openapi/templates/kora/kotlinClientSecuritySchema.mustache
OpenAPI generator HTTP client primaryAuth parameter available for config fixed
=> OpenAPI generator primaryAuth fixed

test/test-junit5/src/main/java/ru/tinkoff/kora/test/extension/junit5/GraphReplacementNoDeps.java, test/test-junit5/src/main/java/ru/tinkoff/kora/test/extension/junit5/GraphReplacementWithDeps.java, test/test-junit5/src/main/java/ru/tinkoff/kora/test/extension/junit5/GraphUtils.java, test/test-junit5/src/main/java/ru/tinkoff/kora/test/extension/junit5/KoraGraphModification.java, test/test-junit5/src/main/java/ru/tinkoff/kora/test/extension/junit5/KoraJUnit5Extension.java, test/test-junit5/src/main/java/ru/tinkoff/kora/test/extension/junit5/TestGraph.java, test/test-junit5/src/test/java/ru/tinkoff/kora/test/extension/junit5/inject/InjectFieldsTests.java, test/test-junit5/src/test/java/ru/tinkoff/kora/test/extension/junit5/inject/InjectMethodArgumentsTests.java, test/test-junit5/src/test/java/ru/tinkoff/kora/test/extension/junit5/inject/InjectWrapperTests.java, test/test-junit5/src/test/java/ru/tinkoff/kora/test/extension/junit5/mockito/MockGraphModificationMockTests.java, test/test-junit5/src/test/java/ru/tinkoff/kora/test/extension/junit5/testdata/TestApplication.java
- Wrapped support for KoraJUnit5Extension fixed
- KoraGraphModification#mockComponent with dependencies removal added
=> KoraJUnit5Extension `Wrapped` support fixed

.github/workflows/publish-release.yml, .github/workflows/test-pr.yml
=> Telegram release notification

http/http-server-undertow/src/main/java/ru/tinkoff/kora/http/server/undertow/UndertowHttpServerModule.java, http/http-server-undertow/src/main/java/ru/tinkoff/kora/http/server/undertow/UndertowModule.java
Undertow Xnio Executor with tag
=> Undertow Xnio Executor Tagged

openapi/openapi-generator/src/main/java/ru/tinkoff/kora/openapi/generator/KoraCodegen.java, openapi/openapi-generator/src/test/java/ru/tinkoff/kora/openapi/generator/KoraCodegenTest.java, openapi/openapi-generator/src/test/resources/example/petstoreV3_types.yaml
URI, duration, time types supported
=> OpenAPI type format fixed

dependencies.gradle
- dependencies.gradle fix versions updated
=> Dependencies with fixes

build.gradle
build.gradle timeout publish increase
=> Publish timeout increase

openapi/openapi-generator/src/main/resources/openapi/templates/kora/javaServerSecuritySchema.mustache, openapi/openapi-generator/src/main/resources/openapi/templates/kora/kotlinServerSecuritySchema.mustache
OpenAPI HTTP Server Cookie AUTH support added
=> OpenAPI Server Cookie auth

scheduling/scheduling-quartz/src/main/java/ru/tinkoff/kora/scheduling/quartz/ScheduleWithCron.java
ScheduleWithCron javadoc improved
=> ScheduleWithCron javadoc

.github/workflows/test-pr.yml, scheduling/scheduling-quartz/src/main/java/ru/tinkoff/kora/scheduling/quartz/ScheduleWithCron.java
ScheduleWithCron fixed
test-pr.yml javadoc check added
=> Javadoc fixed

http/http-server-undertow/src/main/java/ru/tinkoff/kora/http/server/undertow/UndertowHttpServerModule.java, http/http-server-undertow/src/main/java/ru/tinkoff/kora/http/server/undertow/UndertowModule.java
ByteBufferPool factory to private module UndertowModule, now it is in Public API module
=> ByteBufferPool factory for private module

database/database-annotation-processor/src/main/java/ru/tinkoff/kora/database/annotation/processor/jdbc/JdbcRepositoryGenerator.java
Require NonNull for future fixed
=> Require NonNull for future fixed

http/http-server-common/src/main/java/ru/tinkoff/kora/http/server/common/PrivateApiHandler.java
- PrivateApiHandler handling in case of error improved
=> PrivateApiHandler error handling

openapi/openapi-generator/src/main/resources/openapi/templates/kora/javaClientSecuritySchema.mustache, openapi/openapi-generator/src/main/resources/openapi/templates/kora/javaServerSecuritySchema.mustache, openapi/openapi-generator/src/main/resources/openapi/templates/kora/kotlinClientSecuritySchema.mustache, openapi/openapi-generator/src/main/resources/openapi/templates/kora/kotlinServerSecuritySchema.mustache
OpenAPI Kotlin class & method name collision
=> OpenAPI Name collision

config/config-common/src/main/java/ru/tinkoff/kora/config/common/ConfigWatcher.java
ConfigWatcher env & prop renamed
=> ConfigWatcher env & prop renamed

http/http-client-async/build.gradle
Netty native transport dependency module name exclusion typo fixed
=> Async HTTP Client Netty dependency cleanup

annotation-processor-common/src/testFixtures/java/ru/tinkoff/kora/annotation/processor/common/AbstractAnnotationProcessorTest.java, database/database-annotation-processor/src/main/java/ru/tinkoff/kora/database/annotation/processor/entity/DbEntity.java, database/database-annotation-processor/src/test/java/ru/tinkoff/kora/database/common/annotation/processor/jdbc/AbstractJdbcEntityTest.java, database/database-annotation-processor/src/test/java/ru/tinkoff/kora/database/common/annotation/processor/jdbc/JdbcEmbeddedEntityTest.java, database/database-annotation-processor/src/test/java/ru/tinkoff/kora/database/common/annotation/processor/jdbc/JdbcEntityTest.java
- Database record constructor nullable check
```java
public record EmbeddedRecord(String f1, int f2) {
public EmbeddedRecord(@Nullable String f1, int f2) {
this.f1 = f1;
this.f2 = f2;
}
}
```
=> Database record constructor nullable check

annotation-processor-common/src/main/java/ru/tinkoff/kora/annotation/processor/common/CommonClassNames.java, database/database-annotation-processor/src/main/java/ru/tinkoff/kora/database/annotation/processor/cassandra/CassandraRepositoryGenerator.java, database/database-annotation-processor/src/main/java/ru/tinkoff/kora/database/annotation/processor/jdbc/JdbcRepositoryGenerator.java, database/database-annotation-processor/src/main/java/ru/tinkoff/kora/database/annotation/processor/r2dbc/R2dbcRepositoryGenerator.java, database/database-symbol-processor/src/main/kotlin/ru/tinkoff/kora/database/symbol/processor/cassandra/CassandraRepositoryGenerator.kt, database/database-symbol-processor/src/main/kotlin/ru/tinkoff/kora/database/symbol/processor/jdbc/JdbcRepositoryGenerator.kt, database/database-symbol-processor/src/main/kotlin/ru/tinkoff/kora/database/symbol/processor/r2dbc/R2DbcRepositoryGenerator.kt, database/database-symbol-processor/src/main/kotlin/ru/tinkoff/kora/database/symbol/processor/vertx/VertxRepositoryGenerator.kt, database/database-symbol-processor/src/test/kotlin/ru/tinkoff/kora/database/symbol/processor/jdbc/JdbcResultsTest.kt, database/database-vertx/src/main/java/ru/tinkoff/kora/database/vertx/VertxRepositoryHelper.java, symbol-processor-common/src/main/kotlin/ru/tinkoff/kora/ksp/common/CommonClassNames.kt
Database tracing context fork missing fixed
=> Database tracing fixed

database/database-vertx/src/main/java/ru/tinkoff/kora/database/vertx/VertxDatabase.java, database/database-vertx/src/main/java/ru/tinkoff/kora/database/vertx/VertxDatabaseModule.java, database/database-vertx/src/test/java/ru/tinkoff/kora/database/vertx/VertxConnectionFactoryTest.java, grpc/grpc-client-annotation-processor/src/test/java/ru/tinkoff/grpc/client/annotation/processor/GrpcClientExtensionTest.java, grpc/grpc-client-symbol-processor/src/test/kotlin/ru/tinkoff/grpc/client/ksp/GrpcClientExtensionTest.kt, grpc/grpc-client/src/main/java/ru/tinkoff/grpc/client/GrpcClientModule.java, grpc/grpc-client/src/main/java/ru/tinkoff/grpc/client/GrpcNettyClientChannelFactory.java, grpc/grpc-server/src/main/java/ru/tinkoff/kora/grpc/server/GrpcServerModule.java, http/http-client-async/src/main/java/ru/tinkoff/kora/http/client/async/AsyncHttpClientModule.java, netty-common/build.gradle, netty-common/src/main/java/ru/tinkoff/kora/netty/common/NettyChannelFactory.java, netty-common/src/main/java/ru/tinkoff/kora/netty/common/NettyCommonModule.java, netty-common/src/main/java/ru/tinkoff/kora/netty/common/NettyTransportConfig.java, vertx-common/src/main/java/ru/tinkoff/kora/vertx/common/VertxEventLoopGroupTransport.java, vertx-common/src/main/java/ru/tinkoff/kora/vertx/common/VertxUtil.java
NettyTransportConfig added for possible transport selection if multiple available
=> Netty transport selection

openapi/openapi-generator/src/main/resources/openapi/templates/kora/javaClientAsyncResponseMappers.mustache, openapi/openapi-generator/src/main/resources/openapi/templates/kora/javaClientResponseMappers.mustache, openapi/openapi-generator/src/main/resources/openapi/templates/kora/kotlinClientAsyncResponseMappers.mustache, openapi/openapi-generator/src/main/resources/openapi/templates/kora/kotlinClientResponseMappers.mustache, openapi/openapi-generator/src/test/resources/example/petstoreV3_security_api_key.yaml
OpenAPI Generator HTTP Client missing header in response error message improved
=> OpenAPI Generator Client error message improved

database/database-annotation-processor/src/main/java/ru/tinkoff/kora/database/annotation/processor/cassandra/CassandraRepositoryGenerator.java
CassandraRepositoryGenerator CompletableFuture signature support
=> Cassandra CompletableFuture signature

database/database-annotation-processor/src/main/java/ru/tinkoff/kora/database/annotation/processor/cassandra/CassandraRepositoryGenerator.java, database/database-annotation-processor/src/main/java/ru/tinkoff/kora/database/annotation/processor/jdbc/JdbcRepositoryGenerator.java, database/database-annotation-processor/src/main/java/ru/tinkoff/kora/database/annotation/processor/r2dbc/R2dbcRepositoryGenerator.java, database/database-annotation-processor/src/main/java/ru/tinkoff/kora/database/annotation/processor/vertx/VertxRepositoryGenerator.java, database/database-symbol-processor/src/main/kotlin/ru/tinkoff/kora/database/symbol/processor/cassandra/CassandraRepositoryGenerator.kt, database/database-symbol-processor/src/main/kotlin/ru/tinkoff/kora/database/symbol/processor/jdbc/JdbcRepositoryGenerator.kt, database/database-symbol-processor/src/main/kotlin/ru/tinkoff/kora/database/symbol/processor/r2dbc/R2DbcRepositoryGenerator.kt, database/database-symbol-processor/src/main/kotlin/ru/tinkoff/kora/database/symbol/processor/vertx/VertxRepositoryGenerator.kt
Database query context optimization
=> Database repository optimization

grpc/grpc-server/src/main/java/ru/tinkoff/kora/grpc/server/telemetry/GrpcServerMetrics.java, grpc/grpc-server/src/main/java/ru/tinkoff/kora/grpc/server/telemetry/GrpcServerTracer.java, micrometer/micrometer-module/src/main/java/ru/tinkoff/kora/micrometer/module/grpc/server/Opentelemetry120GrpcServerMetrics.java, micrometer/micrometer-module/src/main/java/ru/tinkoff/kora/micrometer/module/grpc/server/Opentelemetry123GrpcServerMetrics.java, opentelemetry/opentelemetry-module/src/main/java/ru/tinkoff/kora/opentelemetry/module/grpc/server/OpentelemetryGrpcServerSpan.java
=> Fix npe in grpc server metrics

dependencies.gradle, micrometer/micrometer-module/build.gradle
=> Prometheus JMX removed

http/http-server-common/src/main/java/ru/tinkoff/kora/http/server/common/handler/HttpServerResponseEntityMapper.java
HttpServerResponseEntityMapper content type preserved from result fixed (fixed #89 )
=> Content-Type for Entity response preserved

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
=> Issue templates fixed

database/database-liquibase/build.gradle, database/database-liquibase/src/main/java/ru/tinkoff/kora/database/liquibase/LiquibaseConfig.java, database/database-liquibase/src/main/java/ru/tinkoff/kora/database/liquibase/LiquibaseJdbcDatabaseInterceptor.java, database/database-liquibase/src/main/java/ru/tinkoff/kora/database/liquibase/LiquibaseJdbcDatabaseModule.java, database/database-liquibase/src/test/java/ru.tinkoff.kora.database.liquibase/LiquibaseJdbcDatabaseInterceptorTest.java, database/database-liquibase/src/test/resources/db/changelog/db.changelog-master.xml, dependencies.gradle, settings.gradle
=> Add liquibase module

database/database-flyway/build.gradle, database/database-flyway/src/main/java/ru/tinkoff/kora/database/flyway/FlywayConfig.java, database/database-flyway/src/main/java/ru/tinkoff/kora/database/flyway/FlywayJdbcDatabaseInterceptor.java, database/database-flyway/src/main/java/ru/tinkoff/kora/database/flyway/FlywayJdbcDatabaseModule.java, database/database-flyway/src/test/java/ru/tinkoff/kora/database/flyway/FlywayJdbcDatabaseInterceptorTest.java
=> FlywayConfig added

grpc/grpc-client/src/main/java/ru/tinkoff/grpc/client/ManagedChannelLifecycle.java, grpc/grpc-server/src/main/java/ru/tinkoff/kora/grpc/server/GrpcServerModule.java
gRPC interceptor execution order fixed
=> gRPC interceptor execution order

common/src/main/java/ru/tinkoff/kora/common/util/Size.java, common/src/test/java/ru/tinkoff/kora/common/naming/SizeTests.java, config/config-common/src/main/java/ru/tinkoff/kora/config/common/DefaultConfigExtractorsModule.java, config/config-common/src/main/java/ru/tinkoff/kora/config/common/extractor/SizeConfigValueExtractor.java
Size type to specifying bytes/mb/gb and etc added
=> Size type added

grpc/grpc-server/src/main/java/ru/tinkoff/kora/grpc/server/GrpcServerModule.java, grpc/grpc-server/src/main/java/ru/tinkoff/kora/grpc/server/config/GrpcServerConfig.java
gRPC Max message size config option added
=> gRPC server message size

kafka/kafka/src/main/java/ru/tinkoff/kora/kafka/common/consumer/containers/KafkaAssignConsumerContainer.java
KafkaAssignConsumerContainer offset duration in millis fixed
=> KafkaAssignConsumerContainer offset duration fixed

test/test-junit5/src/main/java/ru/tinkoff/kora/test/extension/junit5/KoraJUnit5Extension.java, test/test-junit5/src/main/java/ru/tinkoff/kora/test/extension/junit5/TestGraph.java
Testing MDC clear and logging improved
=> JUnit MDC clear

database/database-annotation-processor/src/main/java/ru/tinkoff/kora/database/annotation/processor/QueryMacrosParser.java, database/database-symbol-processor/src/main/kotlin/ru/tinkoff/kora/database/symbol/processor/QueryMacrosParser.kt
QueryMacrosParser fail on native types
=> Macros fail on native types

http/http-server-undertow/src/main/java/ru/tinkoff/kora/http/server/undertow/UndertowExchangeProcessor.java
UndertowExchangeProcessor error exchange content type set
=> HTTP Server error content type set fixed

kafka/kafka/src/main/java/ru/tinkoff/kora/kafka/common/consumer/containers/handlers/impl/RecordHandler.java, kafka/kafka/src/main/java/ru/tinkoff/kora/kafka/common/consumer/containers/handlers/impl/RecordsHandler.java, kafka/kafka/src/main/java/ru/tinkoff/kora/kafka/common/consumer/containers/handlers/wrapper/HandlerWrapper.java, kafka/kafka/src/main/java/ru/tinkoff/kora/kafka/common/consumer/telemetry/KafkaConsumerMetrics.java, micrometer/micrometer-module/src/main/java/ru/tinkoff/kora/micrometer/module/kafka/consumer/Opentelemetry120KafkaConsumerMetrics.java, micrometer/micrometer-module/src/main/java/ru/tinkoff/kora/micrometer/module/kafka/consumer/Opentelemetry123KafkaConsumerMetrics.java
Remove telemetry collection when records is empty
=> Kafka Listener empty telemetry removed

json/json-annotation-processor/src/main/java/ru/tinkoff/kora/json/annotation/processor/reader/EnumReaderGenerator.java, json/json-annotation-processor/src/main/java/ru/tinkoff/kora/json/annotation/processor/reader/JsonReaderGenerator.java, json/json-annotation-processor/src/main/java/ru/tinkoff/kora/json/annotation/processor/reader/SealedInterfaceReaderGenerator.java, json/json-symbol-processor/src/main/kotlin/ru/tinkoff/kora/json/ksp/reader/JsonReaderGenerator.kt, json/json-symbol-processor/src/main/kotlin/ru/tinkoff/kora/json/ksp/reader/SealedInterfaceReaderGenerator.kt
Avoid potential variable and field collision in JsonReader
=> JsonReader potential name collision fix

README.md, json/json-annotation-processor/src/main/java/ru/tinkoff/kora/json/annotation/processor/extension/JsonKoraExtension.java, json/json-symbol-processor/src/main/kotlin/ru/tinkoff/kora/json/ksp/extension/JsonKoraExtension.kt
Kotlin JSON Writer/Reader find constructor fallback strategy
=> Kotlin JSON extension constructor fallback

annotation-processor-common/src/main/java/ru/tinkoff/kora/annotation/processor/common/NameUtils.java, annotation-processor-common/src/testFixtures/java/ru/tinkoff/kora/annotation/processor/common/CompileResult.java, kafka/kafka-annotation-processor/src/main/java/ru/tinkoff/kora/kafka/annotation/processor/consumer/KafkaConsumerConfigGenerator.java, kafka/kafka-annotation-processor/src/main/java/ru/tinkoff/kora/kafka/annotation/processor/consumer/KafkaConsumerContainerGenerator.java, kafka/kafka-annotation-processor/src/main/java/ru/tinkoff/kora/kafka/annotation/processor/consumer/KafkaConsumerHandlerGenerator.java, kafka/kafka-annotation-processor/src/main/java/ru/tinkoff/kora/kafka/annotation/processor/consumer/KafkaConsumerModuleGenerator.java, kafka/kafka-annotation-processor/src/main/java/ru/tinkoff/kora/kafka/annotation/processor/utils/KafkaPublisherUtils.java, kafka/kafka-annotation-processor/src/main/java/ru/tinkoff/kora/kafka/annotation/processor/utils/KafkaUtils.java, kafka/kafka-annotation-processor/src/test/java/ru/tinkoff/kora/kafka/annotation/processor/consumer/AbstractKafkaListenerAnnotationProcessorTest.java, kafka/kafka-annotation-processor/src/test/java/ru/tinkoff/kora/kafka/annotation/processor/consumer/KafkaListenerKeyAndValueTest.java, kafka/kafka-symbol-processor/src/main/kotlin/ru/tinkoff/kora/kafka/symbol/processor/KafkaUtils.kt, kafka/kafka-symbol-processor/src/main/kotlin/ru/tinkoff/kora/kafka/symbol/processor/consumer/KafkaConsumerConfigGenerator.kt, kafka/kafka-symbol-processor/src/main/kotlin/ru/tinkoff/kora/kafka/symbol/processor/consumer/KafkaConsumerModuleGenerator.kt, kafka/kafka-symbol-processor/src/main/kotlin/ru/tinkoff/kora/kafka/symbol/processor/consumer/KafkaContainerGenerator.kt, kafka/kafka-symbol-processor/src/main/kotlin/ru/tinkoff/kora/kafka/symbol/processor/consumer/KafkaHandlerGenerator.kt, kafka/kafka-symbol-processor/src/test/kotlin/ru/tinkoff/kora/kafka/symbol/processor/consumer/KafkaListenerKeyAndValueTest.kt, kafka/kafka/src/main/java/ru/tinkoff/kora/kafka/common/annotation/KafkaListener.java, symbol-processor-common/src/main/kotlin/ru/tinkoff/kora/ksp/common/TagUtils.kt
KafkaListener user tag support added
=> KafkaListener user tag support

http/http-client-annotation-processor/src/main/java/ru/tinkoff/kora/http/client/annotation/processor/ClientClassGenerator.java, http/http-client-annotation-processor/src/test/java/ru/tinkoff/kora/http/client/annotation/processor/BlockingApiTest.java, http/http-client-symbol-processor/src/main/kotlin/ru/tinkoff/kora/http/client/symbol/processor/ClientClassGenerator.kt, http/http-client-symbol-processor/src/test/kotlin/ru/tinkoff/kora/http/client/symbol/processor/BlockingApiTest.kt
HttpClient `@Component` annotation preserved
=> HttpClient `@Component` annotation preserved

annotation-processor-common/src/testFixtures/java/ru/tinkoff/kora/annotation/processor/common/AbstractAnnotationProcessorTest.java, logging/declarative-logging/declarative-logging-annotation-processor/build.gradle, logging/declarative-logging/declarative-logging-annotation-processor/src/main/java/ru/tinkoff/kora/logging/aspect/LogAspect.java, logging/declarative-logging/declarative-logging-annotation-processor/src/test/java/ru/tinkoff/kora/logging/aspect/AbstractLogAspectTest.java, logging/declarative-logging/declarative-logging-annotation-processor/src/test/java/ru/tinkoff/kora/logging/aspect/LogAspectFluxTest.java, logging/declarative-logging/declarative-logging-annotation-processor/src/test/java/ru/tinkoff/kora/logging/aspect/LogAspectMonoTest.java, logging/declarative-logging/declarative-logging-annotation-processor/src/test/java/ru/tinkoff/kora/logging/aspect/LogAspectTest.java, logging/declarative-logging/declarative-logging-symbol-processor/src/main/kotlin/ru/tinkoff/kora/logging/symbol/processor/aop/LogKoraAspect.kt, logging/declarative-logging/declarative-logging-symbol-processor/src/test/kotlin/ru/tinkoff/kora/logging/symbol/processor/aop/AbstractLogAspectTest.kt, logging/declarative-logging/declarative-logging-symbol-processor/src/test/kotlin/ru/tinkoff/kora/logging/symbol/processor/aop/LogAspectFlowTest.kt, logging/declarative-logging/declarative-logging-symbol-processor/src/test/kotlin/ru/tinkoff/kora/logging/symbol/processor/aop/LogAspectTest.kt, symbol-processor-common/src/main/kotlin/ru/tinkoff/kora/ksp/common/FunctionUtils.kt
Logging AOP support for exception handling
Logging AOP support for Flux/Flow
=> Logging AOP improvements

annotation-processor-common/src/main/java/ru/tinkoff/kora/annotation/processor/common/AnnotationUtils.java, annotation-processor-common/src/main/java/ru/tinkoff/kora/annotation/processor/common/TagUtils.java, kafka/kafka-annotation-processor/src/main/java/ru/tinkoff/kora/kafka/annotation/processor/KafkaClassNames.java, kafka/kafka-annotation-processor/src/main/java/ru/tinkoff/kora/kafka/annotation/processor/consumer/KafkaConsumerContainerGenerator.java, kafka/kafka-annotation-processor/src/test/java/ru/tinkoff/kora/kafka/annotation/processor/consumer/KafkaListenerKeyAndValueTest.java, kafka/kafka-annotation-processor/src/test/java/ru/tinkoff/kora/kafka/annotation/processor/consumer/KafkaListenerRecordTest.java, kafka/kafka-annotation-processor/src/test/java/ru/tinkoff/kora/kafka/annotation/processor/consumer/KafkaListenerRecordsTest.java, kafka/kafka-symbol-processor/src/main/kotlin/ru/tinkoff/kora/kafka/symbol/processor/KafkaClassNames.kt, kafka/kafka-symbol-processor/src/main/kotlin/ru/tinkoff/kora/kafka/symbol/processor/consumer/KafkaContainerGenerator.kt, kafka/kafka-symbol-processor/src/test/kotlin/ru/tinkoff/kora/kafka/symbol/processor/consumer/KafkaListenerKeyAndValueTest.kt, kafka/kafka-symbol-processor/src/test/kotlin/ru/tinkoff/kora/kafka/symbol/processor/consumer/KafkaListenerRecordTest.kt, kafka/kafka-symbol-processor/src/test/kotlin/ru/tinkoff/kora/kafka/symbol/processor/consumer/KafkaListenerRecordsTest.kt, kafka/kafka/src/main/java/ru/tinkoff/kora/kafka/common/KafkaUtils.java, kafka/kafka/src/main/java/ru/tinkoff/kora/kafka/common/consumer/ConsumerAwareRebalanceListener.java, kafka/kafka/src/main/java/ru/tinkoff/kora/kafka/common/consumer/containers/KafkaSubscribeConsumerContainer.java, kora-app-annotation-processor/src/test/java/ru/tinkoff/kora/kora/app/annotation/processor/ComponentTest.java, kora-app-annotation-processor/src/test/java/ru/tinkoff/kora/kora/app/annotation/processor/DependencyTest.java, kora-app-symbol-processor/src/main/kotlin/ru/tinkoff/kora/kora/app/ksp/GraphBuilder.kt, kora-app-symbol-processor/src/main/kotlin/ru/tinkoff/kora/kora/app/ksp/component/ComponentDependencyHelper.kt, symbol-processor-common/src/main/kotlin/ru/tinkoff/kora/ksp/common/AnnotationUtils.kt, symbol-processor-common/src/main/kotlin/ru/tinkoff/kora/ksp/common/TagUtils.kt, symbol-processor-common/src/main/kotlin/ru/tinkoff/kora/ksp/common/exception/UnknownTypeError.kt
ConsumerRebalanceListener support added
=> KafkaListener support for ConsumerRebalanceListener added

openapi/openapi-management/src/main/java/ru/tinkoff/kora/openapi/management/OpenApiHttpServerHandler.java, openapi/openapi-management/src/main/java/ru/tinkoff/kora/openapi/management/OpenApiManagementConfig.java, openapi/openapi-management/src/main/java/ru/tinkoff/kora/openapi/management/OpenApiManagementModule.java, openapi/openapi-management/src/main/java/ru/tinkoff/kora/openapi/management/RapidocHttpServerHandler.java, openapi/openapi-management/src/main/java/ru/tinkoff/kora/openapi/management/ResourceUtils.java, openapi/openapi-management/src/main/java/ru/tinkoff/kora/openapi/management/SwaggerUIHttpServerHandler.java, openapi/openapi-management/src/main/resources/META-INF/native-image/ru.tinkoff.kora.openapi.management/resource-config.json, openapi/openapi-management/src/main/resources/kora/openapi/management/swagger-ui/index.html
OpenAPI management multi file support for OpenAPI and Swagger UI endpoints
=> OpenAPI management multi file support

kafka/kafka/src/main/java/ru/tinkoff/kora/kafka/common/consumer/containers/handlers/impl/RecordHandler.java, kafka/kafka/src/main/java/ru/tinkoff/kora/kafka/common/consumer/containers/handlers/impl/RecordsHandler.java
Kafka RecordHandler commit offset+1 fixed
Kafka RecordHandler commit wakeup() interrupt fixed
=> Kafka Consumer record commit fixed

annotation-processor-common/src/main/java/ru/tinkoff/kora/annotation/processor/common/CommonUtils.java, database/database-annotation-processor/src/main/java/ru/tinkoff/kora/database/annotation/processor/jdbc/JdbcRepositoryGenerator.java, database/database-annotation-processor/src/main/java/ru/tinkoff/kora/database/annotation/processor/r2dbc/R2dbcRepositoryGenerator.java, database/database-annotation-processor/src/main/java/ru/tinkoff/kora/database/annotation/processor/vertx/VertxRepositoryGenerator.java, database/database-annotation-processor/src/test/java/ru/tinkoff/kora/database/common/annotation/processor/jdbc/JdbcResultsTest.java, database/database-annotation-processor/src/test/java/ru/tinkoff/kora/database/common/annotation/processor/r2dbc/MockR2dbcExecutor.java, database/database-annotation-processor/src/test/java/ru/tinkoff/kora/database/common/annotation/processor/r2dbc/R2dbcResultsTest.java, database/database-annotation-processor/src/test/java/ru/tinkoff/kora/database/common/annotation/processor/vertx/VertxResultsTest.java, database/database-symbol-processor/src/main/kotlin/ru/tinkoff/kora/database/symbol/processor/jdbc/JdbcRepositoryGenerator.kt, database/database-symbol-processor/src/main/kotlin/ru/tinkoff/kora/database/symbol/processor/r2dbc/R2DbcRepositoryGenerator.kt, database/database-symbol-processor/src/main/kotlin/ru/tinkoff/kora/database/symbol/processor/vertx/VertxRepositoryGenerator.kt
Batch parameter exception handling
=> Batch parameter exception handling

openapi/openapi-generator/src/main/java/ru/tinkoff/kora/openapi/generator/KoraCodegen.java, openapi/openapi-generator/src/main/resources/openapi/templates/kora/javaClientApi.mustache, openapi/openapi-generator/src/main/resources/openapi/templates/kora/javaClientApiOptionalParams.mustache, openapi/openapi-generator/src/main/resources/openapi/templates/kora/kotlinAnnotatedParams.mustache, openapi/openapi-generator/src/main/resources/openapi/templates/kora/kotlinClientApi.mustache, openapi/openapi-generator/src/test/resources/example/petstoreV3_request_parameters.yaml
enum without model default value fixed
string parameter default value fixed
array arg default value fixed
date/datetime/uri/bigint default value support
=> OpenAPI default values fixed

annotation-processor-common/src/main/java/ru/tinkoff/kora/annotation/processor/common/TagUtils.java, aop/aop-annotation-processor/src/main/java/ru/tinkoff/kora/aop/annotation/processor/AopProcessor.java, kafka/kafka-annotation-processor/src/main/java/ru/tinkoff/kora/kafka/annotation/processor/consumer/KafkaConsumerContainerGenerator.java, kora-app-annotation-processor/src/main/java/ru/tinkoff/kora/kora/app/annotation/processor/KoraAppProcessor.java, kora-app-annotation-processor/src/main/java/ru/tinkoff/kora/kora/app/annotation/processor/component/ComponentDependencyHelper.java, kora-app-annotation-processor/src/test/java/ru/tinkoff/kora/kora/app/annotation/processor/app/AppWithAppPart.java, kora-app-symbol-processor/src/test/kotlin/ru/tinkoff/kora/kora/app/ksp/app/AppWithAppPart.kt
KoraSubModule Nullable annotation missing for method factory components
=> KoraSubModule Nullable missing fixed

openapi/openapi-generator/src/main/java/ru/tinkoff/kora/openapi/generator/KoraCodegen.java
CodegenModel required when may be missing
=> OpenAPI CodegenModel required when non validated fixed

http/http-server-annotation-processor/src/main/java/ru/tinkoff/kora/http/server/annotation/processor/RequestHandlerGenerator.java
=> HTTP Server potential primitive fix

openapi/openapi-generator/src/main/resources/openapi/templates/kora/javaEnumClass.mustache, openapi/openapi-generator/src/main/resources/openapi/templates/kora/javaModel.mustache, openapi/openapi-generator/src/main/resources/openapi/templates/kora/kotlinEnumClass.mustache, openapi/openapi-generator/src/main/resources/openapi/templates/kora/kotlinModel.mustache, openapi/openapi-generator/src/test/java/ru/tinkoff/kora/openapi/generator/KoraCodegenTest.java
OpenAPI Additional annotations support
=> OpenAPI additional annotations support

openapi/openapi-generator/src/main/java/ru/tinkoff/kora/openapi/generator/KoraCodegen.java
Date-Time mapping support added (closes #130)
=> Date-Time mapping support added

database/database-symbol-processor/src/main/kotlin/ru/tinkoff/kora/database/symbol/processor/jdbc/JdbcNativeTypes.kt
JdbcNativeTypes LocalDate for Kotlin fixed
=> JdbcNativeTypes LocalDate for Kotlin fixed

http/http-client-common/src/main/java/ru/tinkoff/kora/http/client/common/interceptor/TelemetryInterceptor.java, http/http-client-common/src/main/java/ru/tinkoff/kora/http/client/common/request/DefaultHttpClientRequest.java, http/http-client-common/src/main/java/ru/tinkoff/kora/http/client/common/telemetry/DefaultHttpClientTelemetry.java, http/http-client-common/src/main/java/ru/tinkoff/kora/http/client/common/telemetry/HttpClientLogger.java, http/http-client-common/src/main/java/ru/tinkoff/kora/http/client/common/telemetry/HttpClientMetrics.java, http/http-client-common/src/main/java/ru/tinkoff/kora/http/client/common/telemetry/HttpClientTracer.java, http/http-client-common/src/main/java/ru/tinkoff/kora/http/client/common/telemetry/Sl4fjHttpClientLogger.java, http/http-client-common/src/test/java/ru/tinkoff/kora/http/client/common/telemetry/DefaultHttpClientTelemetryTest.java, http/http-client-common/src/test/java/ru/tinkoff/kora/http/client/common/telemetry/Sl4fjHttpClientLoggerTests.java, http/http-client-common/src/testFixtures/java/ru/tinkoff/kora/http/client/common/HttpClientTest.java, http/http-server-common/src/main/java/ru/tinkoff/kora/http/server/common/router/PublicApiResponseImpl.java, http/http-server-common/src/main/java/ru/tinkoff/kora/http/server/common/telemetry/DefaultHttpServerTelemetry.java, http/http-server-common/src/main/java/ru/tinkoff/kora/http/server/common/telemetry/HttpServerLogger.java, http/http-server-common/src/main/java/ru/tinkoff/kora/http/server/common/telemetry/HttpServerMetrics.java, http/http-server-common/src/main/java/ru/tinkoff/kora/http/server/common/telemetry/HttpServerTelemetry.java, http/http-server-common/src/main/java/ru/tinkoff/kora/http/server/common/telemetry/Slf4jHttpServerLogger.java, http/http-server-common/src/main/java/ru/tinkoff/kora/http/server/common/telemetry/Slf4jHttpServerLoggerFactory.java, http/http-server-common/src/test/java/ru/tinkoff/kora/http/server/common/telemetry/Slf4jHttpServerLoggerTests.java, http/http-server-common/src/testFixtures/java/ru/tinkoff/kora/http/server/common/HttpServerTestKit.java, micrometer/micrometer-module/src/main/java/ru/tinkoff/kora/micrometer/module/http/client/Opentelemetry120HttpClientMetrics.java, micrometer/micrometer-module/src/main/java/ru/tinkoff/kora/micrometer/module/http/client/Opentelemetry123HttpClientMetrics.java, micrometer/micrometer-module/src/main/java/ru/tinkoff/kora/micrometer/module/http/server/Opentelemetry120HttpServerMetrics.java, micrometer/micrometer-module/src/main/java/ru/tinkoff/kora/micrometer/module/http/server/Opentelemetry123HttpServerMetrics.java, opentelemetry/opentelemetry-module/src/main/java/ru/tinkoff/kora/opentelemetry/module/http/client/OpentelemetryHttpClientTracer.java, opentelemetry/opentelemetry-module/src/main/java/ru/tinkoff/kora/opentelemetry/module/http/server/OpentelemetryHttpServerTracer.java, resilient/resilient-annotation-processor/build.gradle, validation/validation-annotation-processor/build.gradle
HTTP Client & Server metrics enriched
=> HTTP Client & Server metrics enriched

maven-parent/build.gradle, openapi/openapi-generator/src/main/java/ru/tinkoff/kora/openapi/generator/KoraCodegen.java, openapi/openapi-generator/src/main/resources/openapi/templates/kora/javaAsyncServerApi.mustache, openapi/openapi-generator/src/main/resources/openapi/templates/kora/javaClientApi.mustache, openapi/openapi-generator/src/main/resources/openapi/templates/kora/javaServerApi.mustache, openapi/openapi-generator/src/main/resources/openapi/templates/kora/kotlinClientApi.mustache, openapi/openapi-generator/src/main/resources/openapi/templates/kora/kotlinServerApi.mustache
Additional contract annotations support for Client & Server OpenAPI generator
=> OpenAPI additional contract annotations

config/config-common/src/main/java/ru/tinkoff/kora/config/common/extractor/EnumConfigValueExtractor.java
EnumConfigValueExtractor enum as toString
=> Enum config value as toString

json/json-common/src/main/java/ru/tinkoff/kora/json/common/ListJsonReader.java, json/json-common/src/main/java/ru/tinkoff/kora/json/common/MapJsonReader.java, json/json-common/src/main/java/ru/tinkoff/kora/json/common/SetJsonReader.java, json/json-common/src/main/java/ru/tinkoff/kora/json/common/SortedSetJsonReader.java
JsonReader Set & Map as Linked to save order
Preventive optimization for single element in list/set/map
=> JsonReader Set & Map as Linked

micrometer/micrometer-module/src/main/java/ru/tinkoff/kora/micrometer/module/grpc/client/Opentelemetry120GrpcClientMetrics.java, micrometer/micrometer-module/src/main/java/ru/tinkoff/kora/micrometer/module/grpc/client/Opentelemetry123GrpcClientMetrics.java, micrometer/micrometer-module/src/main/java/ru/tinkoff/kora/micrometer/module/grpc/server/MicrometerGrpcServerMetricsFactory.java, micrometer/micrometer-module/src/main/java/ru/tinkoff/kora/micrometer/module/grpc/server/Opentelemetry120GrpcServerMetrics.java, micrometer/micrometer-module/src/main/java/ru/tinkoff/kora/micrometer/module/grpc/server/Opentelemetry123GrpcServerMetrics.java
gRPC metrics leaked  due to caching map collision fixed
=> gRPC metrics leak fixed

resilient/resilient-kora/src/main/java/ru/tinkoff/kora/resilient/retry/KoraRetry.java, resilient/resilient-kora/src/main/java/ru/tinkoff/kora/resilient/retry/KoraRetryReactorBuilder.java, resilient/resilient-kora/src/main/java/ru/tinkoff/kora/resilient/retry/RetryConfig.java, resilient/resilient-symbol-processor/src/main/kotlin/ru/tinkoff/kora/resilient/symbol/processor/aop/RetryKoraAspect.kt
=> Retry support zero attempts

application-graph/src/main/java/ru/tinkoff/kora/application/graph/internal/GraphImpl.java, application-graph/src/main/java/ru/tinkoff/kora/application/graph/internal/loom/VirtualThreadExecutorHolder.java, resilient/resilient-kora/src/main/java/ru/tinkoff/kora/resilient/retry/KoraRetry.java, resilient/resilient-kora/src/main/java/ru/tinkoff/kora/resilient/timeout/KoraTimeout.java, resilient/resilient-kora/src/main/java/ru/tinkoff/kora/resilient/timeout/TimeoutExecutor.java, resilient/resilient-kora/src/main/java/ru/tinkoff/kora/resilient/timeout/TimeoutModule.java
Resilient Retry & Timeout virtual thread support
=> Resilient Retry & Timeout virtual thread support

kora-app-annotation-processor/src/main/java/ru/tinkoff/kora/kora/app/annotation/processor/ComponentTemplateHelper.java, kora-app-annotation-processor/src/main/java/ru/tinkoff/kora/kora/app/annotation/processor/GraphBuilder.java, kora-app-annotation-processor/src/test/java/ru/tinkoff/kora/kora/app/annotation/processor/KoraAppProcessorTest.java, kora-app-annotation-processor/src/test/java/ru/tinkoff/kora/kora/app/annotation/processor/app/AppWithFactories13.java, kora-app-symbol-processor/src/test/kotlin/ru/tinkoff/kora/kora/app/ksp/KoraAppKspTest.kt, kora-app-symbol-processor/src/test/kotlin/ru/tinkoff/kora/kora/app/ksp/app/AppWithFactories13.kt
GraphBuilder intersected generics support
=> GraphBuilder intersected generics support

http/http-client-common/src/main/java/ru/tinkoff/kora/http/client/common/telemetry/Sl4fjHttpClientLoggerFactory.java
Sl4fjHttpClientLoggerFactory config enabled check fixed
=> HTTP client logging enabled fixed

database/database-annotation-processor/src/main/java/ru/tinkoff/kora/database/annotation/processor/jdbc/JdbcRepositoryGenerator.java, database/database-symbol-processor/src/main/kotlin/ru/tinkoff/kora/database/symbol/processor/jdbc/JdbcEntityGenerator.kt, database/database-symbol-processor/src/main/kotlin/ru/tinkoff/kora/database/symbol/processor/jdbc/JdbcRepositoryGenerator.kt
Jdbc Kotlin ResultSet.next() check fixed
Jdbc NPE mapping error message improved
=> Jdbc Kotlin ResultSet.next() check fixed

http/http-client-async/src/main/java/ru/tinkoff/kora/http/client/async/response/EmptyAsyncHttpClientResponse.java, http/http-client-async/src/main/java/ru/tinkoff/kora/http/client/async/response/SingleBufferAsyncHttpClientResponse.java, http/http-client-async/src/main/java/ru/tinkoff/kora/http/client/async/response/StreamingAsyncHttpClientResponse.java, http/http-client-common/src/main/java/ru/tinkoff/kora/http/client/common/request/DefaultHttpClientRequest.java, http/http-client-common/src/main/java/ru/tinkoff/kora/http/client/common/response/HttpClientResponse.java, http/http-client-common/src/main/java/ru/tinkoff/kora/http/client/common/telemetry/DefaultHttpClientTelemetryResponseWrapper.java, http/http-client-jdk/src/main/java/ru/tinkoff/kora/http/client/jdk/JdkHttpClientResponse.java, http/http-client-ok/src/main/java/ru/tinkoff/kora/http/client/ok/OkHttpResponse.java, http/http-common/src/main/java/ru/tinkoff/kora/http/common/HttpResponseEntityImpl.java, http/http-server-common/src/main/java/ru/tinkoff/kora/http/server/common/HttpServerResponseException.java, http/http-server-common/src/main/java/ru/tinkoff/kora/http/server/common/SimpleHttpServerResponse.java, http/http-server-common/src/main/java/ru/tinkoff/kora/http/server/common/router/LazyRequest.java
HTTP Client/Server Request/Response toString added
=> HTTP models toString added

database/database-annotation-processor/src/main/java/ru/tinkoff/kora/database/annotation/processor/jdbc/JdbcRepositoryGenerator.java, database/database-symbol-processor/src/main/kotlin/ru/tinkoff/kora/database/symbol/processor/jdbc/JdbcRepositoryGenerator.kt, database/database-symbol-processor/src/test/kotlin/ru/tinkoff/kora/database/symbol/processor/jdbc/JdbcParametersTest.kt
Simplify JDBC execute and remove getUpdateCount if result is Void/Unit
=> JDBC minor optimization

.github/workflows/publish-release.yml, .github/workflows/publish-snapshot.yml
=> CI arguments fixed

opentelemetry/opentelemetry-module/src/main/java/ru/tinkoff/kora/opentelemetry/module/camunda/engine/bpmn/OpentelemetryCamundaEngineBpmnTracer.java, opentelemetry/opentelemetry-module/src/main/java/ru/tinkoff/kora/opentelemetry/module/grpc/client/OpentelemetryGrpcClientRequestSpan.java, opentelemetry/opentelemetry-module/src/main/java/ru/tinkoff/kora/opentelemetry/module/grpc/client/OpentelemetryGrpcClientResponseSpan.java, opentelemetry/opentelemetry-module/src/main/java/ru/tinkoff/kora/opentelemetry/module/grpc/client/OpentelemetryGrpcClientSpan.java, opentelemetry/opentelemetry-module/src/main/java/ru/tinkoff/kora/opentelemetry/module/grpc/client/OpentelemetryGrpcClientTracer.java, opentelemetry/opentelemetry-module/src/main/java/ru/tinkoff/kora/opentelemetry/module/kafka/consumer/OpentelemetryKafkaConsumerTracer.java, opentelemetry/opentelemetry-module/src/main/java/ru/tinkoff/kora/opentelemetry/module/s3/client/OpentelemetryS3ClientTracer.java, opentelemetry/opentelemetry-module/src/main/java/ru/tinkoff/kora/opentelemetry/module/s3/client/OpentelemetryS3KoraClientTracer.java, opentelemetry/opentelemetry-module/src/main/java/ru/tinkoff/kora/opentelemetry/module/scheduling/OpentelemetrySchedulingTracer.java
Tracing status code ERROR fixed
=> Tracing status code fixed

database/database-annotation-processor/src/main/java/ru/tinkoff/kora/database/annotation/processor/jdbc/JdbcEntityAnnotationProcessor.java, database/database-annotation-processor/src/main/java/ru/tinkoff/kora/database/annotation/processor/jdbc/extension/JdbcTypesExtension.java, database/database-symbol-processor/src/main/kotlin/ru/tinkoff/kora/database/symbol/processor/jdbc/JdbcEntitySymbolProcessor.kt, database/database-symbol-processor/src/main/kotlin/ru/tinkoff/kora/database/symbol/processor/jdbc/extension/JdbcTypesExtension.kt
=> EntityJdbc typo fixed

kora-app-annotation-processor/src/main/java/ru/tinkoff/kora/kora/app/annotation/processor/KoraAppProcessor.java, kora-app-symbol-processor/src/main/kotlin/ru/tinkoff/kora/kora/app/ksp/KoraAppProcessor.kt
KoraAppProcessor main module with `$` symbol prefix
=> KoraAppProcessor main module generated prefix

grpc/grpc-server/src/main/java/ru/tinkoff/kora/grpc/server/GrpcNettyServer.java, grpc/grpc-server/src/main/java/ru/tinkoff/kora/grpc/server/GrpcServerModule.java, grpc/grpc-server/src/main/java/ru/tinkoff/kora/grpc/server/config/GrpcServerConfig.java, http/http-server-common/src/main/java/ru/tinkoff/kora/http/server/common/HttpServerConfig.java, http/http-server-undertow/src/main/java/ru/tinkoff/kora/http/server/undertow/UndertowHttpServer.java, kafka/kafka/src/main/java/ru/tinkoff/kora/kafka/common/consumer/KafkaListenerConfig.java, kafka/kafka/src/main/java/ru/tinkoff/kora/kafka/common/consumer/containers/KafkaAssignConsumerContainer.java, kafka/kafka/src/main/java/ru/tinkoff/kora/kafka/common/consumer/containers/KafkaSubscribeConsumerContainer.java, kafka/kafka/src/test/java/ru/tinkoff/kora/kafka/common/containers/KafkaAssignConsumerContainerTest.java, kafka/kafka/src/test/java/ru/tinkoff/kora/kafka/common/containers/KafkaSubscribeConsumerContainerTest.java, scheduling/scheduling-jdk/src/main/java/ru/tinkoff/kora/scheduling/jdk/DefaultJdkSchedulingExecutor.java, scheduling/scheduling-jdk/src/main/java/ru/tinkoff/kora/scheduling/jdk/ScheduledExecutorServiceConfig.java, scheduling/scheduling-jdk/src/main/java/ru/tinkoff/kora/scheduling/jdk/SchedulingJdkConfig.java, scheduling/scheduling-jdk/src/main/java/ru/tinkoff/kora/scheduling/jdk/SchedulingJdkModule.java, scheduling/scheduling-quartz/src/main/java/ru/tinkoff/kora/scheduling/quartz/KoraQuartzJobRegistrar.java, scheduling/scheduling-quartz/src/main/java/ru/tinkoff/kora/scheduling/quartz/QuartzModule.java, scheduling/scheduling-quartz/src/main/java/ru/tinkoff/kora/scheduling/quartz/SchedulingQuartzConfig.java
Graceful shutdown improved for:
- HTTP Server
- gRPC Server
- Kafka Listener
- Jdk Scheduling
- Quartz Scheduling
=> Graceful shutdown improved

.github/workflows/test-master.yml, .github/workflows/test-pr.yml, kafka/kafka-annotation-processor/src/main/java/ru/tinkoff/kora/kafka/annotation/processor/consumer/KafkaConsumerContainerGenerator.java, kafka/kafka-symbol-processor/src/main/kotlin/ru/tinkoff/kora/kafka/symbol/processor/consumer/KafkaContainerGenerator.kt, kafka/kafka/src/main/java/ru/tinkoff/kora/kafka/common/consumer/KafkaListenerConfig.java, kafka/kafka/src/main/java/ru/tinkoff/kora/kafka/common/consumer/containers/handlers/impl/RecordsHandler.java, kafka/kafka/src/main/java/ru/tinkoff/kora/kafka/common/consumer/containers/handlers/wrapper/HandlerWrapper.java, kafka/kafka/src/test/java/ru/tinkoff/kora/kafka/common/containers/KafkaAssignConsumerContainerTest.java, kafka/kafka/src/test/java/ru/tinkoff/kora/kafka/common/containers/KafkaSubscribeConsumerContainerTest.java
KafkaConsumer allow empty records config parameter
=> KafkaConsumer allow empty records

kafka/kafka-symbol-processor/src/main/kotlin/ru/tinkoff/kora/kafka/symbol/processor/producer/KafkaPublisherSymbolProcessor.kt
KafkaProducer allow defaults (non-abstract) methods
=> KafkaProducer allow defaults methods

scheduling/scheduling-quartz/build.gradle
Quartz config processor missing
=> Quartz config processor missing

grpc/grpc-server/src/main/java/ru/tinkoff/kora/grpc/server/GrpcNettyServer.java, kafka/kafka/src/main/java/ru/tinkoff/kora/kafka/common/consumer/containers/KafkaAssignConsumerContainer.java, kafka/kafka/src/main/java/ru/tinkoff/kora/kafka/common/consumer/containers/KafkaSubscribeConsumerContainer.java, scheduling/scheduling-jdk/src/main/java/ru/tinkoff/kora/scheduling/jdk/DefaultJdkSchedulingExecutor.java
Try force shutdownNow if possible when graceful shutdown fails
=> Force shutdown of graceful shutdown fails

scheduling/scheduling-quartz/src/main/java/ru/tinkoff/kora/scheduling/quartz/QuartzModule.java
QuartzModule method collision fix
=> QuartzModule method collision fix

scheduling/scheduling-jdk/src/main/java/ru/tinkoff/kora/scheduling/jdk/AbstractJob.java
Jdk Scheduling do not interrupt immediately await graceful shutdown
=> Jdk Scheduling Job await graceful shutdown

experimental/camunda-rest-undertow/src/main/java/ru/tinkoff/kora/camunda/rest/undertow/UndertowCamundaHttpServer.java, grpc/grpc-server/src/main/java/ru/tinkoff/kora/grpc/server/GrpcNettyServer.java, http/http-server-undertow/src/main/java/ru/tinkoff/kora/http/server/undertow/UndertowHttpServer.java, scheduling/scheduling-quartz/src/main/java/ru/tinkoff/kora/scheduling/quartz/KoraQuartzJobRegistrar.java, scheduling/scheduling-quartz/src/main/java/ru/tinkoff/kora/scheduling/quartz/KoraQuartzScheduler.java, scheduling/scheduling-quartz/src/main/java/ru/tinkoff/kora/scheduling/quartz/QuartzModule.java
Quartz job shutdown improved and reinforced
=> Quartz job shutdown reinforced

dependencies.gradle
Dependency minors version updated
=> Dependency minors version updated

http/http-server-common/src/main/java/ru/tinkoff/kora/http/server/common/HttpServerConfig.java, http/http-server-common/src/test/java/ru/tinkoff/kora/http/server/common/router/PublicApiHandlerProcessTests.java, http/http-server-common/src/test/java/ru/tinkoff/kora/http/server/common/router/PublicApiHandlerTest.java, http/http-server-common/src/testFixtures/java/ru/tinkoff/kora/http/server/common/HttpServerTestKit.java, http/http-server-undertow/src/main/java/ru/tinkoff/kora/http/server/undertow/UndertowHttpServer.java, http/http-server-undertow/src/main/java/ru/tinkoff/kora/http/server/undertow/XnioLifecycle.java
HttpServerConfig enriched with socket and keep-alive options
=> HttpServerConfig enriched

config/config-annotation-processor/src/main/java/ru/tinkoff/kora/config/annotation/processor/ConfigParserGenerator.java, config/config-annotation-processor/src/main/java/ru/tinkoff/kora/config/annotation/processor/ConfigUtils.java, config/config-annotation-processor/src/test/java/ru/tinkoff/kora/config/annotation/processor/AnnotationConfigTest.java, config/config-symbol-processor/src/main/kotlin/ru/tinkoff/kora/config/ksp/ConfigParserGenerator.kt, config/config-symbol-processor/src/test/kotlin/ru/tinkoff/kora/config/symbol/processor/AnnotationConfigTest.kt, grpc/grpc-client-annotation-processor/src/test/java/ru/tinkoff/grpc/client/annotation/processor/GrpcClientExtensionTest.java, grpc/grpc-client-symbol-processor/src/test/kotlin/ru/tinkoff/grpc/client/ksp/GrpcClientExtensionTest.kt, http/http-client-annotation-processor/src/test/java/ru/tinkoff/kora/http/client/annotation/processor/AbstractHttpClientTest.java, http/http-client-symbol-processor/src/test/kotlin/ru/tinkoff/kora/http/client/symbol/processor/AbstractHttpClientTest.kt, scheduling/scheduling-quartz/src/test/java/ru/tinkoff/kora/scheduling/quartz/KoraQuartzJobRegistrarTest.java
Config boolean parameter as native-supported type
=> Config boolean as native type

http/http-server-undertow/src/main/java/ru/tinkoff/kora/http/server/undertow/UndertowHttpServer.java, http/http-server-undertow/src/main/java/ru/tinkoff/kora/http/server/undertow/UndertowPrivateHttpServer.java
UndertowPrivateHttpServer sleep removed
=> HttpServer private release sleep removed

config/config-common/src/main/java/ru/tinkoff/kora/config/common/origin/ResourceConfigOrigin.java
ResourceConfigOrigin#description fixed (closes #204 )
=> ResourceConfigOrigin#description fixed

openapi/openapi-generator/src/main/java/ru/tinkoff/kora/openapi/generator/KoraCodegen.java, openapi/openapi-generator/src/main/resources/openapi/templates/kora/javaModel.mustache, openapi/openapi-generator/src/main/resources/openapi/templates/kora/kotlinModel.mustache, openapi/openapi-generator/src/test/resources/example/petstoreV3_discriminator.yaml
Discriminator field presence improved and reinforced and tests reinforced
Improves some commons (#207)
=> OpenAPI Generator discriminator improved

resilient/resilient-kora/src/main/java/ru/tinkoff/kora/resilient/ResilientException.java, resilient/resilient-kora/src/main/java/ru/tinkoff/kora/resilient/circuitbreaker/CallNotPermittedException.java, resilient/resilient-kora/src/main/java/ru/tinkoff/kora/resilient/retry/KoraRetry.java, resilient/resilient-kora/src/main/java/ru/tinkoff/kora/resilient/retry/KoraRetryReactorBuilder.java, resilient/resilient-kora/src/main/java/ru/tinkoff/kora/resilient/retry/RetryExhaustedException.java, resilient/resilient-symbol-processor/src/main/kotlin/ru/tinkoff/kora/resilient/symbol/processor/aop/RetryKoraAspect.kt
=> ResilientException reinforced

experimental/camunda-zeebe-worker/src/main/java/ru/tinkoff/kora/camunda/zeebe/worker/ZeebeClientConfig.java, experimental/camunda-zeebe-worker/src/main/java/ru/tinkoff/kora/camunda/zeebe/worker/ZeebeManagedChannelFactory.java, experimental/camunda-zeebe-worker/src/main/java/ru/tinkoff/kora/camunda/zeebe/worker/ZeebeWorkerConfig.java, experimental/camunda-zeebe-worker/src/main/java/ru/tinkoff/kora/camunda/zeebe/worker/ZeebeWorkerModule.java
=> Zeebe config reinforced

scheduling/scheduling-quartz/src/main/java/ru/tinkoff/kora/scheduling/quartz/KoraQuartzScheduler.java, scheduling/scheduling-quartz/src/main/java/ru/tinkoff/kora/scheduling/quartz/QuartzModule.java, scheduling/scheduling-quartz/src/test/java/ru/tinkoff/kora/scheduling/quartz/KoraQuartzConfigTests.java
Quartz default properties values fixed
=> Quartz default properties values fixed

openapi/openapi-generator/src/main/java/ru/tinkoff/kora/openapi/generator/KoraCodegen.java, openapi/openapi-generator/src/test/resources/example/petstoreV3_discriminator.yaml
OpenAPI discriminator enum naming fixed
=> OpenAPI discriminator enum naming fixed

validation/validation-module/src/main/java/ru/tinkoff/kora/validation/module/http/server/ValidationHttpServerInterceptor.java
ViolationExceptionHttpServerResponseMapper context added
=> ViolationExceptionHttpServerResponseMapper context added

database/database-cassandra/src/main/java/ru/tinkoff/kora/database/cassandra/CassandraModule.java
Cassandra row mapper for primitive return types invalid index retrival fixed
=> Cassandra row mapper for primitive return types fixed

http/http-server-annotation-processor/src/main/java/ru/tinkoff/kora/http/server/annotation/processor/RequestHandlerGenerator.java, http/http-server-annotation-processor/src/test/java/ru/tinkoff/kora/http/server/annotation/processor/AbstractHttpControllerTest.java, http/http-server-annotation-processor/src/test/java/ru/tinkoff/kora/http/server/annotation/processor/ControllerParamsTest.java, http/http-server-common/src/main/java/ru/tinkoff/kora/http/server/common/StringParameterReadersModule.java, http/http-server-common/src/main/java/ru/tinkoff/kora/http/server/common/handler/RequestHandlerUtils.java, http/http-server-common/src/main/java/ru/tinkoff/kora/http/server/common/handler/StringParameterReader.java, http/http-server-symbol-processor/src/main/kotlin/ru/tinkoff/kora/http/server/symbol/procesor/ExtractorFunctions.kt, http/http-server-symbol-processor/src/main/kotlin/ru/tinkoff/kora/http/server/symbol/procesor/RouteProcessor.kt, http/http-server-symbol-processor/src/test/kotlin/ru/tinkoff/kora/http/server/symbol/processor/AbstractHttpControllerTest.kt, http/http-server-symbol-processor/src/test/kotlin/ru/tinkoff/kora/http/server/symbol/processor/ControllerParamsTest.kt
- HTTP-server enriched out-of-the-box parameters for Headers/Queries/Path with `Set<T>` support
- Correct `List<T>` and `Set<T>` parameter query and header mapping added
=> HTTP-server parameter parsing enriched

database/database-cassandra/src/main/java/ru/tinkoff/kora/database/cassandra/CassandraModule.java
CassandraModule more default mappers added
=> Cassandra more default mappers added

.github/workflows/publish-release.yml
publish-release.yml notify description added
=> publish-release.yml notify description added

application-graph/src/main/java/ru/tinkoff/kora/application/graph/internal/GraphImpl.java
GraphImpl log slow node log type
=> GraphImpl log slow node log type

experimental/s3-client-symbol-processor/src/main/kotlin/ru/tinkoff/kora/s3/client/symbol/processor/S3ClientSymbolProcessor.kt
S3ClientSymbolProcessor kotlin secondary constructor to primary constructor fixed
=> S3Client Kotlin generated constructor fixed

database/database-annotation-processor/src/main/java/ru/tinkoff/kora/database/annotation/processor/DbUtils.java, database/database-annotation-processor/src/main/java/ru/tinkoff/kora/database/annotation/processor/QueryWithParameters.java, database/database-annotation-processor/src/main/java/ru/tinkoff/kora/database/annotation/processor/cassandra/StatementSetterGenerator.java, database/database-annotation-processor/src/main/java/ru/tinkoff/kora/database/annotation/processor/jdbc/StatementSetterGenerator.java, database/database-annotation-processor/src/main/java/ru/tinkoff/kora/database/annotation/processor/r2dbc/R2dbcStatementSetterGenerator.java, database/database-annotation-processor/src/test/java/ru/tinkoff/kora/database/common/annotation/processor/cassandra/CassandraParametersTest.java, database/database-annotation-processor/src/test/java/ru/tinkoff/kora/database/common/annotation/processor/jdbc/JdbcParametersTest.java, database/database-annotation-processor/src/test/java/ru/tinkoff/kora/database/common/annotation/processor/r2dbc/R2dbcParametersTest.java, database/database-symbol-processor/src/main/kotlin/ru/tinkoff/kora/database/symbol/processor/DbUtils.kt, database/database-symbol-processor/src/main/kotlin/ru/tinkoff/kora/database/symbol/processor/QueryWithParameters.kt, database/database-symbol-processor/src/main/kotlin/ru/tinkoff/kora/database/symbol/processor/cassandra/CassandraRepositoryGenerator.kt, database/database-symbol-processor/src/main/kotlin/ru/tinkoff/kora/database/symbol/processor/cassandra/StatementSetterGenerator.kt, database/database-symbol-processor/src/main/kotlin/ru/tinkoff/kora/database/symbol/processor/jdbc/StatementSetterGenerator.kt, database/database-symbol-processor/src/main/kotlin/ru/tinkoff/kora/database/symbol/processor/r2dbc/R2dbcStatementSetterGenerator.kt, database/database-symbol-processor/src/test/kotlin/ru/tinkoff/kora/database/symbol/processor/cassandra/CassandraParametersTest.kt, database/database-symbol-processor/src/test/kotlin/ru/tinkoff/kora/database/symbol/processor/entity/TestEntity.kt, database/database-symbol-processor/src/test/kotlin/ru/tinkoff/kora/database/symbol/processor/jdbc/JdbcParametersTest.kt, database/database-symbol-processor/src/test/kotlin/ru/tinkoff/kora/database/symbol/processor/r2dbc/R2dbcParametersTest.kt, test/test-junit5/src/test/java/ru/tinkoff/kora/test/extension/junit5/mockito/SpyFromFieldPerClassTests.java
Database support for Record/DataClass as self query parameter added
=> Database Record/DataClass self query parameter

database/database-symbol-processor/src/main/kotlin/ru/tinkoff/kora/database/symbol/processor/cassandra/CassandraEntityGenerator.kt, database/database-symbol-processor/src/test/kotlin/ru/tinkoff/kora/database/symbol/processor/cassandra/AbstractCassandraRepositoryTest.kt, database/database-symbol-processor/src/test/kotlin/ru/tinkoff/kora/database/symbol/processor/cassandra/CassandraExtensionTest.kt, database/database-symbol-processor/src/test/kotlin/ru/tinkoff/kora/database/symbol/processor/jdbc/JdbcExtensionTests.kt, database/database-symbol-processor/src/test/kotlin/ru/tinkoff/kora/database/symbol/processor/jdbc/JdbcMacrosTest.kt, database/database-symbol-processor/src/test/kotlin/ru/tinkoff/kora/database/symbol/processor/jdbc/JdbcResultsTest.kt
- Cassandra list mapper when empty resultSet is optimized
- Tests cleanup
=> Cassandra list mapper optimized

openapi/openapi-generator/src/main/java/ru/tinkoff/kora/openapi/generator/KoraCodegen.java
OpenAPI Enum Model variable naming fixed with correct enum datatypeWithEnum name
=> OpenAPI model enum variable naming fixed

http/http-server-common/src/main/java/ru/tinkoff/kora/http/server/common/handler/RequestHandlerUtils.java
RequestHandlerUtils#parseOptionalSomeListQueryParameter headers instead of query parameters
=> `List<T>` and `Set<T>` query parameter parsing fixed

http/soap-client-annotation-processor/src/main/java/ru/tinkoff/kora/soap/client/annotation/processor/SoapClasses.java, http/soap-client-annotation-processor/src/main/java/ru/tinkoff/kora/soap/client/annotation/processor/SoapClientImplGenerator.java, http/soap-client-annotation-processor/src/main/java/ru/tinkoff/kora/soap/client/annotation/processor/WebServiceClientAnnotationProcessor.java, http/soap-client-annotation-processor/src/test/wsdl/simple-service.wsdl, http/soap-client-symbol-processor/src/main/kotlin/ru/tinkoff/kora/soap/client/symbol/processor/SoapClasses.kt, http/soap-client-symbol-processor/src/main/kotlin/ru/tinkoff/kora/soap/client/symbol/processor/SoapClientImplGenerator.kt, http/soap-client-symbol-processor/src/test/wsdl/simple-service.wsdl
add processing wrapped types for requests/responses for SOAP
=> Add processing for xml element wrapped types for requests/responses

openapi/openapi-generator/src/main/resources/openapi/templates/kora/javaModel.mustache
Java model discriminator as required arg constructor fixed
=> Java model discriminator as required arg constructor fixed

openapi/openapi-generator/src/main/java/ru/tinkoff/kora/openapi/generator/KoraCodegen.java, openapi/openapi-generator/src/test/resources/example/petstoreV3_enum.yaml
=> Enum name for arrays fixed

json/json-symbol-processor/src/main/kotlin/ru/tinkoff/kora/json/ksp/extension/JsonKoraExtension.kt
=> Json kora extension should not attempt to generate json mappers for non sealed interfaces

kora-app-annotation-processor/src/main/java/ru/tinkoff/kora/kora/app/annotation/processor/DependencyModuleHintProvider.java, kora-app-symbol-processor/src/main/kotlin/ru/tinkoff/kora/kora/app/ksp/DependencyModuleHintProvider.kt
Graph dependency hint message and match improved
=> Graph dependency hint message and match improved

resilient/resilient-kora/src/main/java/ru/tinkoff/kora/resilient/circuitbreaker/CircuitBreakerConfig.java
CircuitBreakerConfig error message improved
=> CircuitBreakerConfig error message improved

common/src/main/java/ru/tinkoff/kora/common/util/TimeUtils.java, scheduling/scheduling-common/src/main/java/ru/tinkoff/kora/scheduling/common/telemetry/SchedulingLogger.java, scheduling/scheduling-common/src/main/java/ru/tinkoff/kora/scheduling/common/telemetry/Slf4jSchedulingLogger.java, scheduling/scheduling-jdk/src/main/java/ru/tinkoff/kora/scheduling/jdk/AbstractJob.java, scheduling/scheduling-jdk/src/main/java/ru/tinkoff/kora/scheduling/jdk/DefaultJdkSchedulingExecutor.java, scheduling/scheduling-jdk/src/main/java/ru/tinkoff/kora/scheduling/jdk/ScheduledExecutorServiceConfig.java
- JDK Scheduling maxPoolSize->corePoolSize
- Scheduling logging improved
- ScheduledExecutorServiceConfig#threads 20->2
=> JDK scheduling pool potential outOfThreads fixed 

json/json-annotation-processor/src/main/java/ru/tinkoff/kora/json/annotation/processor/JsonUtils.java, json/json-annotation-processor/src/main/java/ru/tinkoff/kora/json/annotation/processor/extension/JsonKoraExtension.java, json/json-annotation-processor/src/main/java/ru/tinkoff/kora/json/annotation/processor/writer/WriterTypeMetaParser.java, json/json-annotation-processor/src/test/java/ru/tinkoff/kora/json/annotation/processor/NativeTypesTest.java, json/json-symbol-processor/src/main/kotlin/ru/tinkoff/kora/json/ksp/JsonUtils.kt, json/json-symbol-processor/src/main/kotlin/ru/tinkoff/kora/json/ksp/extension/JsonKoraExtension.kt, json/json-symbol-processor/src/main/kotlin/ru/tinkoff/kora/json/ksp/writer/WriterTypeMetaParser.kt, json/json-symbol-processor/src/test/kotlin/ru/tinkoff/kora/json/ksp/AbstractJsonSymbolProcessorTest.kt, json/json-symbol-processor/src/test/kotlin/ru/tinkoff/kora/json/ksp/NativeTypesTest.kt, json/json-symbol-processor/src/test/kotlin/ru/tinkoff/kora/json/ksp/SupportedTypesTest.kt
- Json Kotlin accessor check added
- Native package ignore immediately for Json Extension if occurred
=> Json Kotlin accessor check added

test/test-junit5/src/main/java/ru/tinkoff/kora/test/extension/junit5/KoraJUnit5Extension.java, test/test-junit5/src/main/java/ru/tinkoff/kora/test/extension/junit5/TestGraph.java, test/test-junit5/src/main/java/ru/tinkoff/kora/test/extension/junit5/TestGraphContext.java, test/test-junit5/src/main/java/ru/tinkoff/kora/test/extension/junit5/TestGraphInitialized.java, test/test-junit5/src/test/java/ru/tinkoff/kora/test/extension/junit5/initializemode/NestedFieldPerClassNestedTests.java
- Parallel execution with locking on test context and better context injection depending on lifecycle
- Nested test classes execution and error handling reinforced
=> JUnit parallel and nested tests reinforced

resilient/resilient-annotation-processor/src/main/java/ru/tinkoff/kora/resilient/annotation/processor/aop/CircuitBreakerKoraAspect.java, resilient/resilient-annotation-processor/src/main/java/ru/tinkoff/kora/resilient/annotation/processor/aop/FallbackKoraAspect.java, resilient/resilient-annotation-processor/src/main/java/ru/tinkoff/kora/resilient/annotation/processor/aop/TimeoutKoraAspect.java, resilient/resilient-kora/src/main/java/ru/tinkoff/kora/resilient/circuitbreaker/KoraCircuitBreaker.java, resilient/resilient-kora/src/main/java/ru/tinkoff/kora/resilient/timeout/KoraTimeout.java, resilient/resilient-kora/src/test/java/ru/tinkoff/kora/resilient/circuitbreaker/KoraCircuitBreakerTests.java, resilient/resilient-symbol-processor/src/main/kotlin/ru/tinkoff/kora/resilient/symbol/processor/aop/CircuitBreakerKoraAspect.kt, resilient/resilient-symbol-processor/src/main/kotlin/ru/tinkoff/kora/resilient/symbol/processor/aop/RetryKoraAspect.kt
- KoraCircuitBreaker half-open missing proper error counter increment and state switch fixed
- Other resilient modules exception handling reinforced
=> CircuitBreaker half-open proper error count fixed

openapi/openapi-generator/src/main/java/ru/tinkoff/kora/openapi/generator/KoraCodegen.java
Free Form not found for discriminator error handling added
=> OpenAPI discriminator for free Form error handling

cache/cache-redis/src/main/java/ru/tinkoff/kora/cache/redis/AbstractRedisCache.java
AbstractRedisCache NPE for putAsync fixed
=> AbstractRedisCache NPE for putAsync fixed

kafka/kafka/src/main/java/ru/tinkoff/kora/kafka/common/consumer/containers/KafkaAssignConsumerContainer.java
KafkaAssignConsumerContainer report lag add -1 cause of endOffsets contract
=> Kafka metric report lag proper value fixed

experimental/s3-client-annotation-processor/src/main/java/ru/tinkoff/kora/s3/client/annotation/processor/S3ClientAnnotationProcessor.java, experimental/s3-client-symbol-processor/src/main/kotlin/ru/tinkoff/kora/s3/client/symbol/processor/S3ClientSymbolProcessor.kt
S3Client add generated code throws exception
=> S3Client add generated code throws exception

openapi/openapi-generator/src/main/resources/openapi/templates/kora/kotlinServerSecuritySchema.mustache
OpenAPI kotlin kotlinServerSecuritySchema.mustache optimized retrieval like Java template
=> OpenAPI Kotlin Server authorization optimized

openapi/openapi-generator/src/main/java/ru/tinkoff/kora/openapi/generator/KoraCodegen.java, openapi/openapi-generator/src/main/resources/openapi/templates/kora/javaEnumClass.mustache, openapi/openapi-generator/src/main/resources/openapi/templates/kora/kotlinEnumClass.mustache, openapi/openapi-generator/src/test/resources/example/petstoreV3_enum.yaml
OpenAPI Enum constant SnakeCase new additional naming and old one as deprecated
=> OpenAPI Enum constant SnakeCase additional naming

openapi/openapi-generator/src/main/java/ru/tinkoff/kora/openapi/generator/KoraCodegen.java, openapi/openapi-generator/src/test/java/ru/tinkoff/kora/openapi/generator/KoraCodegenTest.java, openapi/openapi-generator/src/test/resources/example/petstoreV3_filter.yaml
OpenAPI `filterWithModels` custom option added to work with [FILTER openapiNormalizer](https://openapi-generator.tech/docs/customization/#available-filters)
=> OpenAPI `filterWithModels` custom option added

openapi/openapi-generator/src/main/java/ru/tinkoff/kora/openapi/generator/KoraCodegen.java, openapi/openapi-generator/src/test/resources/example/petstoreV3_enum.yaml
OpenAPI enum field naming and translite field naming fixed
=> OpenAPI enum field naming and translite field naming fixed

config/config-common/src/main/java/ru/tinkoff/kora/config/common/extractor/EnumConfigValueExtractor.java
Enum config extractor error message improved
=> Enum config extractor error message improved

json/json-annotation-processor/src/main/java/ru/tinkoff/kora/json/annotation/processor/JsonAnnotationProcessor.java, json/json-annotation-processor/src/main/java/ru/tinkoff/kora/json/annotation/processor/extension/JsonKoraExtension.java, json/json-annotation-processor/src/main/java/ru/tinkoff/kora/json/annotation/processor/reader/ReaderTypeMetaParser.java, json/json-annotation-processor/src/main/java/ru/tinkoff/kora/json/annotation/processor/writer/WriterTypeMetaParser.java, json/json-annotation-processor/src/test/java/ru/tinkoff/kora/json/annotation/processor/extension/JsonKoraExtensionTest.java, json/json-symbol-processor/src/main/kotlin/ru/tinkoff/kora/json/ksp/reader/ReaderTypeMetaParser.kt, json/json-symbol-processor/src/main/kotlin/ru/tinkoff/kora/json/ksp/writer/WriterTypeMetaParser.kt, json/json-symbol-processor/src/test/kotlin/ru/tinkoff/kora/json/ksp/extension/JsonKoraExtensionTest.kt
- Json extension sealed type propagation fixed
- Json generator error handling improved
=> Json extension type propagation for sealed fixed

openapi/openapi-generator/src/main/java/ru/tinkoff/kora/openapi/generator/KoraCodegen.java
OpenAPI generator Kotlin model required vars validation visit fixed
=> OpenAPI generator Kotlin model validation fixed

test/test-junit5/src/main/java/ru/tinkoff/kora/test/extension/junit5/GraphMockitoMock.java, test/test-junit5/src/main/java/ru/tinkoff/kora/test/extension/junit5/GraphMockkMock.java, test/test-junit5/src/main/java/ru/tinkoff/kora/test/extension/junit5/GraphUtils.java, test/test-junit5/src/main/java/ru/tinkoff/kora/test/extension/junit5/KoraJUnit5Extension.java, test/test-junit5/src/main/java/ru/tinkoff/kora/test/extension/junit5/MockUtils.java, test/test-junit5/src/test/java/ru/tinkoff/kora/test/extension/junit5/inject/InjectFieldsTests.java, test/test-junit5/src/test/java/ru/tinkoff/kora/test/extension/junit5/inject/InjectInterfacesTests.java, test/test-junit5/src/test/java/ru/tinkoff/kora/test/extension/junit5/inject/InjectParameterGraphTests.java, test/test-junit5/src/test/java/ru/tinkoff/kora/test/extension/junit5/inject/InjectWrapperTests.java, test/test-junit5/src/test/java/ru/tinkoff/kora/test/extension/junit5/mockito/MockWrappedParentTests.java, test/test-junit5/src/test/java/ru/tinkoff/kora/test/extension/junit5/mockito/MockWrappedTests.java, test/test-junit5/src/test/java/ru/tinkoff/kora/test/extension/junit5/testdata/TestApplication.java, test/test-junit5/src/test/kotlin/ru/tinkoff/kora/test/extension/junit5/kotlin/mockk/MockWrappedParentTests.kt, test/test-junit5/src/test/kotlin/ru/tinkoff/kora/test/extension/junit5/kotlin/mockk/MockWrappedTests.kt, test/test-junit5/src/test/kotlin/ru/tinkoff/kora/test/extension/junit5/kotlin/mockk/MockkFieldsTests.kt, test/test-junit5/src/test/kotlin/ru/tinkoff/kora/test/extension/junit5/kotlin/mockk/MockkGraphModificationTests.kt
Kora JUnit test Wrapped child proper support fixed
=> Kora JUnit test Wrapped child proper support fixed

annotation-processor-common/src/main/java/ru/tinkoff/kora/annotation/processor/common/BuildEnvironment.java, kora-app-annotation-processor/src/main/java/ru/tinkoff/kora/kora/app/annotation/processor/GraphResolutionHelper.java, kora-app-annotation-processor/src/main/java/ru/tinkoff/kora/kora/app/annotation/processor/component/ComponentDependency.java, kora-app-annotation-processor/src/main/java/ru/tinkoff/kora/kora/app/annotation/processor/component/DependencyClaim.java, kora-app-annotation-processor/src/main/java/ru/tinkoff/kora/kora/app/annotation/processor/component/ResolvedComponent.java, kora-app-annotation-processor/src/main/java/ru/tinkoff/kora/kora/app/annotation/processor/declaration/ComponentDeclaration.java, kora-app-annotation-processor/src/test/java/ru/tinkoff/kora/kora/app/annotation/processor/KoraAppProcessorTest.java
Java application graph resolution logging and error output improved
=> Improved Graph resolution error output

openapi/openapi-generator/src/main/java/ru/tinkoff/kora/openapi/generator/KoraCodegen.java, openapi/openapi-generator/src/test/java/ru/tinkoff/kora/openapi/generator/KoraCodegenTest.java, openapi/openapi-generator/src/test/resources/example/petstoreV3_filter.yaml
Fixed OpenAPI FILTER with models recursion scan for complex hierarchy
=> Fixed OpenAPI `FILTER` for for complex hierarchy

http/http-client-common/src/main/java/ru/tinkoff/kora/http/client/common/telemetry/DefaultHttpClientTelemetryCollectingResponseBodyWrapper.java
Fixed HTTP-client collecting buffers rewind to further read for body logging
=> Fixed HTTP-client body logging

kora-app-symbol-processor/src/main/kotlin/ru/tinkoff/kora/kora/app/ksp/component/ComponentDependencyHelper.kt, kora-app-symbol-processor/src/main/kotlin/ru/tinkoff/kora/kora/app/ksp/declaration/ComponentDeclaration.kt, kora-app-symbol-processor/src/test/kotlin/ru/tinkoff/kora/kora/app/ksp/InvalidTypeTest.kt
=> KSP error message improved

.github/workflows/publish-release.yml, build.gradle
=> Reinforced release

test/test-junit5/src/main/java/ru/tinkoff/kora/test/extension/junit5/KoraConfigModification.java
=> Allow to set multiple KoraConfigModification system properties from a map

experimental/camunda-zeebe-worker/src/main/java/ru/tinkoff/kora/camunda/zeebe/worker/ZeebeManagedChannelFactory.java, grpc/grpc-client/src/main/java/ru/tinkoff/grpc/client/ManagedChannelLifecycle.java, grpc/grpc-client/src/main/java/ru/tinkoff/grpc/client/config/GrpcClientConfig.java, grpc/grpc-server/src/main/java/ru/tinkoff/kora/grpc/server/GrpcServerModule.java, grpc/grpc-server/src/main/java/ru/tinkoff/kora/grpc/server/config/GrpcServerConfig.java
Добавлены следующие настройки GRPC:
1. KEEPALIVE_TIME и KEEPALIVE_TIMEOUT для клиента и сервера
2. балансировщик для клиента
=> Grpc configuration improvement

cache/cache-redis/src/main/java/ru/tinkoff/kora/cache/redis/lettuce/LettuceClientConfig.java, cache/cache-redis/src/main/java/ru/tinkoff/kora/cache/redis/lettuce/LettuceClientFactory.java, cache/cache-redis/src/test/java/ru/tinkoff/kora/cache/redis/CacheRunner.java
Cache Redis SSL context config added
=> Added Cache Redis SSL config

kafka/kafka/src/main/java/ru/tinkoff/kora/kafka/common/consumer/containers/KafkaAssignConsumerContainer.java
Fix bug with KafkaAssignConsumerContainer consumer restart that stops restarting consumer from reading topic. Also fix consumer start logging.
=> Fix bug with KafkaAssignConsumerContainer on consumer restart

validation/validation-annotation-processor/src/main/java/ru/tinkoff/kora/validation/annotation/processor/ValidatorGenerator.java, validation/validation-annotation-processor/src/main/java/ru/tinkoff/kora/validation/annotation/processor/aop/ValidateMethodKoraAspect.java, validation/validation-annotation-processor/src/test/java/ru/tinkoff/kora/validation/annotation/processor/testdata/ValidateSync.java
- Fixed validate NotNull and Nullable signature
- Fixed validate async Nullable signature
=> Fixed Validation for NotNull and Nullable signatures

http/http-client-annotation-processor/src/main/java/ru/tinkoff/kora/http/client/annotation/processor/ClientClassGenerator.java, http/http-client-annotation-processor/src/main/java/ru/tinkoff/kora/http/client/annotation/processor/HttpClientClassNames.java, http/http-client-annotation-processor/src/main/java/ru/tinkoff/kora/http/client/annotation/processor/Parameter.java, http/http-client-annotation-processor/src/test/java/ru/tinkoff/kora/http/client/annotation/processor/parameters/HttpClientCookieParametersTest.java, http/http-client-symbol-processor/src/main/kotlin/ru/tinkoff/kora/http/client/symbol/processor/ClientClassGenerator.kt, http/http-client-symbol-processor/src/main/kotlin/ru/tinkoff/kora/http/client/symbol/processor/HttpClientClassNames.kt, http/http-client-symbol-processor/src/main/kotlin/ru/tinkoff/kora/http/client/symbol/processor/Parameter.kt, http/http-client-symbol-processor/src/test/kotlin/ru/tinkoff/kora/http/client/symbol/processor/parameters/HttpClientCookieParametersTest.kt, http/http-common/src/main/java/ru/tinkoff/kora/http/common/cookie/Cookie.java, http/http-common/src/main/java/ru/tinkoff/kora/http/common/cookie/CookieImpl.java, http/http-common/src/main/java/ru/tinkoff/kora/http/common/cookie/Cookies.java
Added HTTP Client Cookie support
=> Added HTTP Client Cookie support

micrometer/micrometer-module/src/main/java/ru/tinkoff/kora/micrometer/module/resilient/MicrometerCircuitBreakerMetrics.java, resilient/resilient-kora/src/main/java/ru/tinkoff/kora/resilient/circuitbreaker/CallNotPermittedException.java, resilient/resilient-kora/src/main/java/ru/tinkoff/kora/resilient/circuitbreaker/CircuitBreakerConfig.java, resilient/resilient-kora/src/main/java/ru/tinkoff/kora/resilient/circuitbreaker/CircuitBreakerMetrics.java, resilient/resilient-kora/src/main/java/ru/tinkoff/kora/resilient/circuitbreaker/KoraCircuitBreaker.java, resilient/resilient-kora/src/main/java/ru/tinkoff/kora/resilient/circuitbreaker/NoopCircuitBreakerMetrics.java, resilient/resilient-kora/src/test/java/ru/tinkoff/kora/resilient/circuitbreaker/KoraCircuitBreakerTests.java, resilient/resilient-symbol-processor/build.gradle, resilient/resilient-symbol-processor/src/test/kotlin/ru/tinkoff/kora/resilient/circuitbreaker/CircuitBreakerTests.kt
- Improved Resilient CircuitBreaker error messages and KoraCircuitBreaker#accept handle throwable
- Added Resilient CircuitBreaker metrics for call acquire
=> Improved minor Resilient CircuitBreaker

database/database-annotation-processor/src/main/java/ru/tinkoff/kora/database/annotation/processor/entity/DbEntity.java, database/database-annotation-processor/src/main/java/ru/tinkoff/kora/database/annotation/processor/jdbc/StatementSetterGenerator.java, database/database-annotation-processor/src/test/java/ru/tinkoff/kora/database/common/annotation/processor/jdbc/AbstractJdbcEntityTest.java, database/database-annotation-processor/src/test/java/ru/tinkoff/kora/database/common/annotation/processor/jdbc/JdbcEmbeddedEntityTest.java, database/database-annotation-processor/src/test/java/ru/tinkoff/kora/database/common/annotation/processor/jdbc/JdbcMacrosTest.java, database/database-symbol-processor/src/main/kotlin/ru/tinkoff/kora/database/symbol/processor/DbUtils.kt, database/database-symbol-processor/src/main/kotlin/ru/tinkoff/kora/database/symbol/processor/jdbc/StatementSetterGenerator.kt, database/database-symbol-processor/src/test/kotlin/ru/tinkoff/kora/database/symbol/processor/jdbc/JdbcMacrosTest.kt, symbol-processor-common/src/main/kotlin/ru/tinkoff/kora/ksp/common/FieldFactory.kt
- Fixed Kotlin JDBC Embedded correct field accessor for inner fields
- Fixed Java & Kotlin JDBC Embedded nullable fields and inner fields accessor
=> Fixed JDBC Embedded field accessors

http/http-client-common/src/main/java/ru/tinkoff/kora/http/client/common/telemetry/HttpClientMetrics.java, micrometer/micrometer-module/src/main/java/ru/tinkoff/kora/micrometer/module/MetricsModule.java, micrometer/micrometer-module/src/main/java/ru/tinkoff/kora/micrometer/module/http/client/MicrometerHttpClientMetricsFactory.java, micrometer/micrometer-module/src/main/java/ru/tinkoff/kora/micrometer/module/http/client/Opentelemetry120HttpClientMetrics.java, micrometer/micrometer-module/src/main/java/ru/tinkoff/kora/micrometer/module/http/client/Opentelemetry123HttpClientMetrics.java, micrometer/micrometer-module/src/main/java/ru/tinkoff/kora/micrometer/module/http/client/tag/DurationKey.java, micrometer/micrometer-module/src/main/java/ru/tinkoff/kora/micrometer/module/http/client/tag/MicrometerHttpClientTagsProvider.java, micrometer/micrometer-module/src/main/java/ru/tinkoff/kora/micrometer/module/http/client/tag/Opentelemetry120MicrometerHttpClientTagsProvider.java, micrometer/micrometer-module/src/main/java/ru/tinkoff/kora/micrometer/module/http/client/tag/Opentelemetry123MicrometerHttpClientTagsProvider.java
- Added MicrometerHttpClientTagsProvider for HTTP client
=> Added HTTP client metric tags provider

micrometer/micrometer-module/src/main/java/ru/tinkoff/kora/micrometer/module/MetricsModule.java, micrometer/micrometer-module/src/main/java/ru/tinkoff/kora/micrometer/module/grpc/client/MicrometerGrpcClientMetricsFactory.java, micrometer/micrometer-module/src/main/java/ru/tinkoff/kora/micrometer/module/grpc/client/Opentelemetry120GrpcClientMetrics.java, micrometer/micrometer-module/src/main/java/ru/tinkoff/kora/micrometer/module/grpc/client/Opentelemetry123GrpcClientMetrics.java, micrometer/micrometer-module/src/main/java/ru/tinkoff/kora/micrometer/module/grpc/client/tag/DefaultMicrometerGrpcClientTagsProvider.java, micrometer/micrometer-module/src/main/java/ru/tinkoff/kora/micrometer/module/grpc/client/tag/MessageReceivedKey.java, micrometer/micrometer-module/src/main/java/ru/tinkoff/kora/micrometer/module/grpc/client/tag/MessageSendKey.java, micrometer/micrometer-module/src/main/java/ru/tinkoff/kora/micrometer/module/grpc/client/tag/MethodDurationKey.java, micrometer/micrometer-module/src/main/java/ru/tinkoff/kora/micrometer/module/grpc/client/tag/MetricsKey.java, micrometer/micrometer-module/src/main/java/ru/tinkoff/kora/micrometer/module/grpc/client/tag/MicrometerGrpcClientTagsProvider.java, micrometer/micrometer-module/src/main/java/ru/tinkoff/kora/micrometer/module/grpc/server/tag/DefaultMicrometerGrpcServerTagsProvider.java
- Added MicrometerGrpcClientTagsProvider
=> Added gRPC metric tags provider

cache/cache-redis/build.gradle, cache/cache-redis/src/main/java/ru/tinkoff/kora/cache/redis/lettuce/LettuceClientConfig.java, cache/cache-redis/src/main/java/ru/tinkoff/kora/cache/redis/lettuce/LettuceClientFactory.java, cache/cache-redis/src/main/java/ru/tinkoff/kora/cache/redis/lettuce/LettuceConfigurator.java, cache/cache-redis/src/main/java/ru/tinkoff/kora/cache/redis/lettuce/LettuceModule.java, cache/cache-redis/src/main/java/ru/tinkoff/kora/cache/redis/lettuce/telemetry/CommandLatencyRecorderFactory.java, cache/cache-redis/src/test/java/ru/tinkoff/kora/cache/redis/CacheRunner.java, micrometer/micrometer-module/build.gradle, micrometer/micrometer-module/src/main/java/ru/tinkoff/kora/micrometer/module/MetricsModule.java, micrometer/micrometer-module/src/main/java/ru/tinkoff/kora/micrometer/module/cache/redis/lettuce/MicrometerLettuceCommandLatencyRecorderFactory.java, micrometer/micrometer-module/src/main/java/ru/tinkoff/kora/micrometer/module/cache/redis/lettuce/Opentelemetry120LettuceCommandLatencyRecorder.java, micrometer/micrometer-module/src/main/java/ru/tinkoff/kora/micrometer/module/cache/redis/lettuce/Opentelemetry123LettuceCommandLatencyRecorder.java, micrometer/micrometer-module/src/main/java/ru/tinkoff/kora/micrometer/module/grpc/client/Opentelemetry123GrpcClientMetrics.java
- Redis LettuceConfigurator added
- Redis CommandLatencyRecorderFactory added
- Redis command metrics added
- Redis enchanted lettuce client builder added
- Redis SSL context config added
=> Added Redis Lettuce factory improvements

experimental/s3-client-minio/build.gradle, gradle/libs.versions.toml, gradle/wrapper/gradle-wrapper.properties, http/http-client-ok/build.gradle, opentelemetry/opentelemetry-tracing-exporter-grpc/build.gradle
Fixed Opentelemetry gRPC dependency for OkHttp client
=> Fixed Opentelemetry gRPC dependency for OkHttp client

openapi/openapi-generator/src/main/java/ru/tinkoff/kora/openapi/generator/KoraCodegen.java, openapi/openapi-generator/src/test/resources/example/petstoreV3_discriminator.yaml
Added OpenAPI generator include allOf properties if any specified for discriminator parent model when oneOf is also in place
=> Fixed OpenAPI generator improve `discriminator` parent model

openapi/openapi-generator/build.gradle, openapi/openapi-generator/src/main/java/ru/tinkoff/kora/openapi/generator/KoraCodegen.java, openapi/openapi-generator/src/main/resources/openapi/templates/kora/javaEnumClass.mustache, openapi/openapi-generator/src/main/resources/openapi/templates/kora/javaModel.mustache, openapi/openapi-generator/src/main/resources/openapi/templates/kora/kotlinEnumClass.mustache, openapi/openapi-generator/src/main/resources/openapi/templates/kora/kotlinModel.mustache, openapi/openapi-generator/src/test/java/ru/tinkoff/kora/openapi/generator/KoraCodegenTest.java, openapi/openapi-generator/src/test/resources/example/petstoreV3_nullable.yaml
Fixed OpenAPI generator Kotlin items nullable
=> Fixed OpenAPI generator Kotlin items nullable

kafka/kafka/src/main/java/ru/tinkoff/kora/kafka/common/consumer/containers/ConsumerRecordWrapper.java, kafka/kafka/src/main/java/ru/tinkoff/kora/kafka/common/consumer/containers/ConsumerRecordsWrapper.java, kafka/kafka/src/main/java/ru/tinkoff/kora/kafka/common/consumer/containers/ConsumerWrapper.java
Added ConsumerRecordWrapper#unwrap for accessing original record
=> Added ConsumerRecordWrapper#unwrap for accessing original record

openapi/openapi-generator/src/main/java/ru/tinkoff/kora/openapi/generator/KoraCodegen.java, openapi/openapi-generator/src/test/resources/example/petstoreV3_validation.yaml
Fixed OpenAPI generator Validation schema ref scan loop with StackOverFlow
=> Fixed OpenAPI generator Validation loop sof
